### ISSUE TITLE
Add Role Based Security Rules to Firestore Rules

### ISSUE THREAD

**Issue by sprad** [Recidiviz/covid19-dashboard#118]
At the moment, our [Firestore security rules](https://github.com/Recidiviz/covid19-dashboard/blob/master/backend/firestore.rules) allow any authenticated user to access any "scenario" document.  We should update these rules to ensure that only the user who with the "owner" role can make edits (i.e. read, write, updated, delete)

Note:  user and role information is stored within the `roles` map associated with each `scenario` document.

**Comment by itsjon** [comment]
@sprad since there's not yet a "viewer" feature, I'm updating this issue to only include item 1, `Only the user who with the "owner" role can make edits (i.e. read, write, updated, delete)`.
