### ISSUE TITLE
Load the Facility Form when a Facility Row is Clicked On

### ISSUE THREAD

**Issue by sprad** [Recidiviz/covid19-dashboard#126]
In order to allow users to edit facility data, we should load the Facility form for a given facility when they click on that facility.

Note:  Any edits made in the form should be saved and reflected on the dashboard page when the user clicks save

**Comment by jessex** [comment]
Just clarifying since I don't see this explicit in the mocks. Is this supposed to load the form right on the page and shift other facility rows out of the way? Or navigate away to the page where you can edit a facility model? CC @cawarren
