### ISSUE TITLE
Wire the Scenario Sidebar to Read From and Write To Firestore

### ISSUE THREAD

**Issue by sprad** [Recidiviz/covid19-dashboard#131]
<img width="346" alt="Screen Shot 2020-04-17 at 3 07 19 PM" src="https://user-images.githubusercontent.com/25503/79605040-35eb2a80-80bd-11ea-834f-ce4a8632dc5f.png">

Populate the Scenario Sidebar with information from the Cloud Firestore.  You can get information about the baseline scenario from Firestore by using the following code:

```javascript
const baselineScenarioRef = await getBaselineScenarioRef();
const result = await baselineScenarioRef.get();
const scenario = result.data();
```

Note `getBaselineScenarioRef` can be imported from our [db code](https://github.com/Recidiviz/covid19-dashboard/blob/master/src/database/index.tsx#L135).

For this mockup you'll need the `name`, `updatedAt`, `dailyReports`, and `dataSharing` attributes found on the `scenario` object.

As a final step, when the user toggles the `dailyReports`, and `dataSharing` toggles we should save these updates to Firestore by calling the `saveScenario` method that can also be imported from our [db code](https://github.com/Recidiviz/covid19-dashboard/blob/master/src/database/index.tsx#L210).

```javavscript
  saveScenario({
    dataSharing: true,
  });
```

**Comment by daschi** [comment]
@sprad I don't see `dailyReports` and `dataSharing` on the `scenario` object, will those be added / will they be booleans?

**Comment by sprad** [comment]
@daschi - Great catch.  Can you add those attributes after `baseline` in this code:  https://github.com/Recidiviz/covid19-dashboard/blob/master/src/database/index.tsx#L194

I'll go through and update our existing scenarios manually so that Firestore returns those values

**Comment by sprad** [comment]
@daschi - You can default their values to false

**Comment by daschi** [comment]
@sprad I added the `false` values in the database file and opened a WIP PR here: #136
