### ISSUE TITLE
Figure out a way to remove JSON shenanigans in model persistence

### ISSUE THREAD

**Issue by jessex** [Recidiviz/covid19-dashboard#144]
**What needs to be done? Why does it need to be done?**
As first added and noted [here](https://github.com/Recidiviz/covid19-dashboard/pull/143/files#r410903129), the logic to invoke the model save function from the frontend involves serializing and immediately deserializing the model inputs as json. There should very likely be a better way.

**Comment by szhu** [comment]
This needs to be fixed to make IE11 work.

> Browsers with native Map support serialize Maps as `{}`, browsers without native Map support try to serialize the Map polyfill object and get a circular reference error.
