### ISSUE TITLE
Promo behavior on the sidebar of the Scenario details page

### ISSUE THREAD

**Issue by daschi** [Recidiviz/covid19-dashboard#159]
**What needs to be done? Why does it need to be done?**
The promo on the sidebar of the scenario details page is supposed to have more sophisticated behavior, e.g. permanent dismissal and only displaying in certain  states. We haven’t done anything of the sort yet so we can do this post-release. 

Behavior: 
- Only display 0-1 promos at a time
- Permanent dismissal ( per session )
- Display in certain states (states: )

Questions:
**What are the states this should display for?**
**Which promo takes priority in these cases?**

1. Both toggles are OFF, on baseline scenario page, user has > 3 facilities
2. Both toggles are OFF, on baseline scenario page, user has < 3 facilities
3. One of the toggles is OFF, user has < 3 facilities

**Promo 1:** Turn on 'Daily Reports' to receive briefings based on the data in this scenario, prepared by Recidiviz and CSG.
- Only display if daily reports is OFF and on baseline scenario

**Promo 2:** Turn on 'Data Sharing' to provide your baseline data to public researchers, to help improve models of disease spread in prisons in the future.
- Only display if sharing toggle is OFF and on baseline scenario

**Promo 3:** Add additional facilities to see the impact across your entire system. 
- Only display once per session per scenario (save to scenario model?)
- Only display if user has < 3 facilities 

**Additional context**
See the doc for updated copy & behavior:
https://docs.google.com/spreadsheets/d/1bnBsQXbtrRogruVkDPiAketsHUrv3H26ibw0ydh94D8/edit#gid=1594361286

**Comment by cawarren** [comment]
*Promo behavior*
- Promos should only appear on page load (they shouldn't backfill if one is dismissed, that space should just stay blank).
- A promo that has already been dismissed for a given scenario, shouldn't be shown again for that scenario.

*Promo priority order (higher takes precedence over lower)*
1. Daily Reports (Promo 1)
2. Data Share (Promo 2)
3. Add Facilities (Promo 3)

Here are the additional conditions for each promo:
- Promo 1 only appears if:
  - Current scenario is the baseline scenario, and
  - 'Daily Reports' toggle is OFF
- Promo 2 only appears if:
  - Current scenario is the baseline scenario, and
  - 'Data Sharing' toggle is OFF
- Promo 3 only appears if:
  - Scenario has <3 facilities


Feel free to ping me with any specific questions.

**Comment by daschi** [comment]
@cawarren Awesome thanks for the details! I think the only other question I had was about which states to include it for (@jessex mentioned this should only display for certain states?)

**Comment by jessex** [comment]
Sorry, @daschi, by _states_ I did not mean US States. I meant the conditions that @cawarren spelled out above.

**Comment by daschi** [comment]
Oops, that makes more sense! Sorry I misunderstood :)
