### ISSUE TITLE
Improve inline behavior of input components

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/covid19-dashboard#164]
**Is your feature request related to a problem? Please describe.**
Our designs call for editable text in several places that are expected to behave like normally flowing text rather than a form input field (see, e.g., the Scenario name, the facility names in the list of facilities). Our existing input fields cannot replicate this desired input behavior in all cases (see e.g. wrapping of longer Scenario names in #157 ).

**Describe the solution you'd like**
Some alternative input components based on the HTML TextEditable feature may be desirable, if it's possible to create an interface that mimics our existing text inputs in how they handle data and user input events but allows arbitrary text styling. (`contenteditable` is kind of a messy and poorly supported feature so if it's possible to achieve the desired outcomes with regular form inputs that would be preferable)

**Comment by cawarren** [comment]
Flagging in passing that this may be relevant to #196 and #197 (both also relate to text inputs), in case one should come before others.
