### ISSUE TITLE
Add support for multiple scenarios

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#168]
**Is your feature request related to a problem? Please describe.**
We currently only support the baseline scenario in the web model, but ask that the user keep this model reflecting the real-world. This makes it difficult for the user to adequately forecast different scenarios and what-ifs (e.g., 'What if we were to release some of the low-risk members of the incarcerated population? What if we were to make space to move more people out of bunked housing and into cells?')

**Describe the solution you'd like**
We've scoped support for multiple scenarios beyond the baseline, and should add that support now. This means:
- Addition of a scenarios 'library' to view and open scenarios from
- The ability to rename and delete a scenario

**Additional context**
- [Current mocks](https://www.figma.com/file/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=910%3A130)

**Child issues**
- ~Update model persistence to support saving multiple named scenarios #177~
- ~Update Model Persistence to Support Accessing Multiple Named Scenarios #255~
- ~Add support for duplicating scenarios #175~ 
- ~Add support for deleting scenarios #285~
- ~Add scenario libraries view #176~ 
- ~Remove Icon Coupling from the InputNameWithIcon Component #350 (launch blocker)~
- ~Properly Handle Scenario Change State Management #348 (launch blocker)~
- ~Add the Ability to Delete a Scenario in the Scenario Library #351~
- ~Allow Adding New Scenario in the Scenario Library View #368~
- ~Enhance the Data Visualization in the Scenario Library #347~

**Comment by jessex** [comment]
@cawarren can you decompose this one into sub-issues please? Given how many new UI components it creates, we won't necessarily be able to do everything effectively in one pass. We can create sub-tasks and just have them reference this one by hashtag. Issues I can see:
1. Updates to model persistence to support saving multiple named scenarios
1. Scenarios library view
1. Support for duplicating a scenario (and all of its facility models with it)

And a question: when you first log in, are you supposed to be taken to the baseline scenario, or to be shown the scenario library in a modal? Even if modal, it still needs to be floating above some page, so I still presume baseline in that case?

**Comment by cawarren** [comment]
We should always take the user to their baseline scenario on login.

I'll decompose into the three issues you named.

**Comment by jessex** [comment]
_Clean up, clean up, everybody, everywhere_
