### ISSUE TITLE
Add support for user-to-user sharing

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#169]
**Is your feature request related to a problem? Please describe.**
Currently only the creator of a scenario has access to it, making one member of a research team the bottleneck for several others.

**Describe the solution you'd like**
Add the ability for a user to explicitly share a scenario that they own with another user, and to revoke access. Users will be enumerated by e-mail address, and sharing will only be allowed within the same domain name to start.

**Additional context**
Mocks will be added when available. Backend support for sharing can start prior to UX spec, if eng doesn't feel that UX is likely to impact the implementation approach.

**Child Issues**

- ~Update Firestore Rules to Consider the Viewer Role #428~
- ~Create a User Collection and Associated Firestore Rules #430~
- ~Create a saveUser Function to Store User Information #431~
- ~Store the User’s Auth0 Attributes Upon Signup #432~
- ~Investigate Security Rule Updates to Limit Potential Data Leakage from the User Collection #461~
- ~Create a getUser Function to Retrieve User Information #435~
- ~Create a getScenarioUsers Function to Retrieve a List of Users who can Access a Scenario #436~
- ~Create an addScenarioUser Function to Add a User to a Scenario #437~
- ~Create a removeScenarioUser Function to Remove a User from a Scenario #438~
- ~Update Recidiviz auth0 sign-ups to collect names #419~
- ~Update the getScenarios Function to Consider the viewer Role Type #440~
- ~Add a Read-Only Banner When a User with a viewer Role is visiting a Scenario #442~
- ~Display a Toast Message Upon Firestore Permission Errors #429~
- ~Update the Name Field for All Existing Users in Auth0 #433~
- ~Create a User Document for Each Existing User #434~
- ~Create a Share Scenario Modal #439~
- ~Update the Scenario Library to Show All Scenarios Accessible by a User #441~

**Comment by jessex** [comment]
This will require either being able to translate from an email address to a Firebase user token on the fly, or persisting the email address in the data model directly. You can get the email address on the client side in the `user` object returned through the Auth0 SDK. @itsjon given you put together the Auth0xFirebase token exchange, do you have an idea of how to best approach this?

**Comment by jessex** [comment]
@cawarren does this require the ability to be able to search among a list of users in your domain / that you can share with? Or should it be a lookup attempt where you're not given a list or a hint? The former could be a privacy concern, and also has the extra technical complexity of having to query the Auth0 Management API (have never done this before) to retrieve the set of users that match a certain email domain (which, again, is a potential privacy concern).

**Comment by jessex** [comment]
@cawarren are other users able to edit a model, or only the owner? We previously discussed a progression from no-share to single-editor to multi-editor, but the latter has _a lot_ of hidden complexity that I'm not sure we can/should tackle straight away.

**Comment by cawarren** [comment]
@jessex I don't anticipate auto-lookup at the moment, because of the privacy concern you mentioned. I do anticipate complexity around inviting people who don't use our service yet (we might need to discuss the neatest way to handle that on the technical front).

@jessex Let's assume read-only for now to avoid all of that complexity.

**Comment by itsjon** [comment]
I haven't thought through it fully, but my initial thought was to use a couple cloud functions:

1. Invite function: send the invitation to an email address if the requesting user (verifies via their Firebase token) does have access to the given scenario, and embed in the link in that invitation a JWT that includes the invited user's email address
2. Invite acceptance function: Once the user signs in, verifies their JWT matches their email and then adds them to the scenario's `roles` object as a `viewer`

**Comment by jessex** [comment]
An invitation workflow sounds _fairly complex_ unless there's a drop-in solution available. Otherwise, we're building some workflow from scratch that is capable of generating emails and dealing with the JWT potentially expiring (unless these are permanent per user).

It seems like it might be easier to check if the specified email is attached to any user (with an Auth0 call), returning an error if not, and adding the user as a viewer role to the shared scenario if true. Then on the user who just became a viewer we'd start displaying that scenario in their library and in the scenario details page you would have some UX cues that what you're looking at is not editable by you. You could also add a promo when they open a scenario on which they are not owner which describes that this scenario was shared with you by X (another Auth0 call to determine the email address of the user who shared with you).

**Comment by cawarren** [comment]
Bumping this up in priority because it's a) now one of our most highly requested features, and b) important for Zak's work.

@jessex I think your approach makes sense from Apr 21. Sharing grants read-only access to any user, and our only check when you share is that that user actually exists.

Mocks should follow today, but hopefully we can start on backend work without blocking on them?

**Comment by jessex** [comment]
@sprad I think you should be able to get started on scenario sharing today without the mocks fully in place yet. Let me know if that doesn't sound accurate. 

@macfarlandian, as we discussed the other day, you and Sprad should sync up to see if there's a way to divide the work here. One idea might be for one of you to work on Firebase changes and the other to work on using the Auth0 API as necessary, but of course you two can divide however you see fit.

But given the priority of this, I think having you two tag-team on it in the hopes of getting it released before the week is over seems like a good idea.

(@cawarren: can you confirm that what we are interested in here is sharing an entire scenario, not sharing specific facilities within a scenario?)

**Comment by cawarren** [comment]
Confirmed, we're interested in sharing full scenarios not just facilities.
