### ISSUE TITLE
[Report automation] Generate a weekly PDF report for all 50 states from the admin page

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#170]
Pre-amble: This issue will absolutely need to be broken up into smaller pieces. Pending finalized mocks on all sections. Content for section 3 of the report is ready to build.

**Is your feature request related to a problem? Please describe.**
More details in Phase 2 of the PRD: https://docs.google.com/document/d/1WwT52cF1I-Wmn7FomkUkMxFT93yTtvP8XGCRYuKKRQs/edit#heading=h.rddiepdm76ab

We provide a weekly briefing to a handful of states today, which is a fairly arduous manual data collection process (for them and for us). We are in the process of scaling this report to all 50 states and using the web model as the source of truth.

There is currently no easy way for our team to get the data for each state's report.

Phase 1 (#531) build an admin page and pulled locale stats for each state onto the admin page to remove a layer of manual work.

Phase 2 ([PRD](https://docs.google.com/document/d/1WwT52cF1I-Wmn7FomkUkMxFT93yTtvP8XGCRYuKKRQs/edit#heading=h.rddiepdm76ab)) involves generating the entire PDF report.

**Describe the solution you'd like**
Thanks to shadow baseline work, weekly reports can be generated for all states, even if no one from the state is using the web model. 
- If a state has a particular baseline model that they want to base a report off of (usually the DOC researcher), they need to **1) sync it with shadow baseline, 2) share their model with covid@recidiviz.org**, and a PDF report will be generated using the data in their baseline scenario.
- Otherwise, state reports will be general using a state’s shadow baseline.

**There are 4 sections of the report**
**Section 1:** (Ready to build plumbing, still pending final designs): State YTD summary and impact report. [PRD section](https://docs.google.com/document/d/1WwT52cF1I-Wmn7FomkUkMxFT93yTtvP8XGCRYuKKRQs/edit#heading=h.5l54sjnz0gvl). Issues #587, #588, #589
**Section 2:** (WIP, ready to build except charts): System summary
**Section 3:** (Ready to build plumbing, still pending final designs): Facility 1-pagers ([PRD section](https://docs.google.com/document/d/1WwT52cF1I-Wmn7FomkUkMxFT93yTtvP8XGCRYuKKRQs/edit#heading=h.wv5rk4dz3cna)). Issues #578, #579, #580, #581

**Section 4:** Methodology and About --> this section will remain manual for the time being.

**Describe alternatives you've considered**
We are continuing to generate this report manually in the interim, but we are unable to scale it beyond 10 states based on the time it takes.

**Additional context**
Full detail in weekly report automation [PRD](https://docs.google.com/document/d/1WwT52cF1I-Wmn7FomkUkMxFT93yTtvP8XGCRYuKKRQs/edit#heading=h.o6qhdniolruh)

**Child issues:**
- Add 'admin' user tag in Auth0, pull through to client #183
- Admin page to print locale stats for all states
- Child issues per section above

Edited by: @sychang

**Comment by jessex** [comment]
What defines an admin user? A Recidiviz staff member only or could there be other admins?

**Comment by cawarren** [comment]
@jessex I'd prefer it be a whitelist if feasible (not all Recidiviz accounts).

**Comment by jessex** [comment]
In that case, we need to start tracking who is an admin in Auth0 and pulling that down to the client. I think it's sufficient to manually maintain the whitelist within Auth0 by adding the required metadata tag to the user (and removing when necessary), so the code changes that are necessary here are to replicate what we did in the pulse-dashboard and 1) create a rule within Auth0 to explicitly pass user metadata back in auth requests, and 2) have functions in the app that can pull the admin tag out of the metadata and gate certain pages based on that tag. Would you mind filing an issue for this work specifically, as a child of this task?
