### ISSUE TITLE
Add scenario libraries view

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#176]
**Is your feature request related to a problem? Please describe.**
We currently only support the baseline scenario in the web model, but ask that the user keep this model reflecting the real-world. This makes it difficult for the user to adequately forecast different scenarios and what-ifs (e.g., 'What if we were to release some of the low-risk members of the incarcerated population? What if we were to make space to move more people out of bunked housing and into cells?')

In order to accomplish this, we need a place in the UI for users to view, open, add, or delete their scenarios.

**Describe the solution you'd like**
Creation of the 'Library' modal dialog for viewing the user's scenarios. See mocks below.

**Additional context**
- This is a child issue of issue #168 
- [Current mocks](https://www.figma.com/file/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=910%3A130)

**Comment by amyrlam** [comment]
Is this modal, which would pop up after clicking the InputNameWithIcon folder icon

![image](https://user-images.githubusercontent.com/1372946/80773014-76ab6080-8b0d-11ea-836d-0fef29e552c9.png)

**Comment by jessex** [comment]
Yep! This modal is the library view. We should ask @cawarren whether each chart is meant to be _one_ of the facility model charts for that scenario, say the first one in alphabetical order, or whether it's supposed to be a composite across the entire scenario, like what's happening on the impact page (Excalibur).

**Comment by cawarren** [comment]
The designer's intent was for this to be the summed output for the scenario. If that's challenging from an implementation standpoint though, I'd feel free to grab the first facility chart - really this is eye candy for this view, it's not a functional component of the model output.
