### ISSUE TITLE
Update model persistence to support saving multiple named scenarios

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#177]
**Is your feature request related to a problem? Please describe.**
We currently only support the baseline scenario in the web model, but ask that the user keep this model reflecting the real-world. This makes it difficult for the user to adequately forecast different scenarios and what-ifs (e.g., 'What if we were to release some of the low-risk members of the incarcerated population? What if we were to make space to move more people out of bunked housing and into cells?')

In order to save multiple scenarios, we need to support saving multiple named scenarios associated with a user on the data persistence side.

**Describe the solution you'd like**
Update data model persistence to support multiple saved copies per user. Implement in a way that coexists peacefully with the versioning support mentioned in issue #166.

**Additional context**
This is a child issue of issue #168

**Comment by sprad** [comment]
Setting this issue to "Done" as it was resolved by the work in #129
