### ISSUE TITLE
Switch to using an established build framework (Gatsby or Next.js)

### ISSUE THREAD

**Issue by szhu** [Recidiviz/covid19-dashboard#181]
Our current frontend build system, largely set up by PRs #1, #4, and #16, uses Parcel and a custom script for static rendering.

This system worked well initially, since it was really small and didn't include features we needed to understand but didn't need to use. Over time, the following things have happened:
- We found a few bugs in Parcel, which we've had to work around.
- Many more developers are working on the project simultaneously.
- We needed to make custom tooling to support new features we've added like auth, web manifests, and setting up a backend. Each time we needed to specifically make sure with the frontend build system.

We have these these things that we haven't done yet:
- #80 -- supporting IE11
- #179 -- setting up testing

All of these above would probably be easier to handle if we use a framework that handles a larger set of the things we need out of the box. **Notably, I actually think that it could be easier to switch our build system to a framework  that supports IE11 than to try to hack in IE11 support into our current build system.**

Here are the two major frameworks that do approximately what we want (statically generate an interactive site):
- [Gatsby](https://www.gatsbyjs.org/)
- [Next.js](https://nextjs.org/)

I spent the past few hours looking at their documentation and going through the setup for each, and they both seem easy to use. Some notable reasons to choose each:
- Gatsby seems to support IE11 even when the Node modules we use don't. [[Source](https://www.gatsbyjs.org/docs/browser-support/)] Next.js, on the other hand seems to have issues that are fairly recent regarding this still. The way to solve this seems to require using a third-party plugin.
- Next.js has a framework for server-side functions (haven't looked into whether it's compatible with the backend stuff we need to do), while Gatsby is static-only.
- Gatsby seems more "batteries included" and polished with less technical know-how to get set up.
- Next.js is maintained by ZEIT ([they rebranded yesterday to be called Vercel](https://vercel.com/blog/zeit-is-now-vercel)), which also maintains Now.

It looks like Gatsby is the more appropriate choice at the moment, but I'm still looking into it.

---

Fixes #80 (we will only choose a framework if it supports IE11)

**Comment by jessex** [comment]
Thanks for filing this, @szhu! I did a quick search and I note that there are some SO posts and such talking about Gatsby only supporting IE in production and not in development (i.e. `gatsby develop` might not support IE). I don't think that's a major issue to be clear, but wanted to highlight it. I had not used Parcel before this app and have _only_ used Webpack on React apps, but if Gatsby looks promising and like it won't be a massive effort just to get to the point of testing, then I encourage you to pursue it!

**Comment by jessex** [comment]
Thanks for filing this, @szhu! I did a quick search and I note that there are some SO posts and such talking about Gatsby only supporting IE in production and not in development (i.e. `gatsby develop` might not support IE). I don't think that's a major issue to be clear, but wanted to highlight it.

As for the server-side function support in Next.js, I'm not sure it is relevant to us. This app is not actually building and deploying the cloud function we are using for the auth token exchange with Firebase, as far as I am aware, so I don't _think_ the build choice impacts it. I could be wrong, though! @itsjon would know more than I on this topic.

I had not used Parcel before this app and have _only_ used Webpack on React apps, but if Gatsby looks promising, you don't see a reason why it might not work for us, and like it won't be a massive effort just to get to the point of testing, then I encourage you to pursue it!

**Comment by szhu** [comment]
Progress report -- I'm about 2/3 done with everything:
- Working features: React, TypeScript, routing, fonts, Tailwind, global styles, styled-components, emotion (required for the loader library)
- Missing features: page titles and metadata, login gating, webmanifests

I picked the minimum set of features to get the overview page working.
**Here's a screenshot of it working on IE11:**

![image](https://user-images.githubusercontent.com/1570168/80211526-bdb7c400-85ea-11ea-8acc-80b5a5182d19.png)

**Comment by jessex** [comment]
Very exciting, @szhu! Stellar progress so far.

**Comment by szhu** [comment]
Update: everything works on IE11!

![Screen Shot 2020-04-24 at 5 03 19 PM (2)](https://user-images.githubusercontent.com/1570168/80265802-a3630200-864d-11ea-898a-6f057e89b019.png)
