### ISSUE TITLE
Fix inconsistent text box fields of scenario details page

### ISSUE THREAD

**Issue by jessex** [Recidiviz/covid19-dashboard#196]
**Describe the bug**
Through rapid movement, the three different text boxes on the Scenario Details page have all become different in style/manner:
* The scenario rename field shows a pencil on hover, then you click and it becomes an obvious text box. When you hit enter or click away, it goes back to regular text
* The facility rename field shows a pencil on hover, but when you click the only cue that it is editable is that a cursor starts blinking. There's no style change otherwise
* The scenario description field is just a permanent text box

We should make these a consistent experience for users.

**Expected behavior**
Everything should behave in the manner of the scenario rename field: by default it looks like regular text, a pencil icon is shown on hover, it turns into an obvious text box when you click, and it goes back to normal when you're done.

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

**Additional context**

**Comment by jessex** [comment]
The scenario rename and scenario description fields on the scenario details page been made consistent by #206.

**Comment by amyrlam** [comment]
I can claim this ticket, unless another one seems better. Will take a look at the linked PR's
