### ISSUE TITLE
Add stronger validation for major text fields

### ISSUE THREAD

**Issue by jessex** [Recidiviz/covid19-dashboard#197]
**Describe the bug**
The "major" text fields, e.g. scenario name, facility name, and scenario description, all have little to no validation at present.
* You can fully delete a scenario name and make it blank. If you then want to edit it to re-add a name, you have to click on the folder icon, as nothing else is selectable after the text is gone.
* You can fully delete a facility name. On the facility input form, if you don't enter a facility name, then it gets auto-named as "Unnamed Facility." But then if you delete the name on the scenario details page, it stays fully unnamed.
* You can completely delete a scenario description and make it blank.

**Expected behavior**
You should not be allowed to make any of these fields blank, and the input forms should tell you this if you attempt to click save (in the case of the facility name on the facility input form) or if you attempt to press enter, click outside of the field, or otherwise finish updating a text field on the scenario details page.

**Additional context**
We want the experience to be consistent across all text fields that cannot be made or left blank. Any UI thoughts, @cawarren?

**Comment by cawarren** [comment]
Full list of constraints, including some additional thoughts:
- Facility name and Scenario name are max 124 chars (auto-truncates anything longer)
- Facility name and Scenario name cannot be left blank (won't let you stop editing / save until they're non-blank)
- Scenario description is max 500 chars

**Comment by jessex** [comment]
Thanks, @cawarren! Just a heads up in case it slipped, this is still awaiting triage and has not had its priority set in the TODO column yet.
