### ISSUE TITLE
Add 'Duplicate facility' functionality

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#204]
**Is your feature request related to a problem? Please describe.**
We currently enable users to set up facilities, but some states have dozens of the things. Setting up your baseline scenario could take a long time if you're going through and manually selecting all of the same policy inputs / etc. for each one.

**Describe the solution you'd like**
Add a 'Duplicate facility' button on the Facility Details view, which copies your inputs into a new facility and puts you in the Facility Details view of the new one. This let's a user fill out facility info once, then make copies and just update name / population info.

Note: There's no expectation of any meaningful relationship between the original and duplicated facilities. This is solely a convenience feature to copy inputs from an already-entered facility into a new one.

**Additional context**
- [Mocks](https://www.figma.com/file/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=1636%3A130) (see Duplicate Facility button at the top of the Facility Details view)

**Comment by cawarren** [comment]
Now blocked on redesign due to #304

**Comment by daschi** [comment]
@cawarren Just want to confirm--should this only duplicate name, description, and the latest inputs, and not include the historical case and population numbers?

**Comment by daschi** [comment]
update from @cawarren to include facility versions!
