### ISSUE TITLE
Facility List - "delete" button should move to Edit Facility View > "..." menu

### ISSUE THREAD

**Issue by rocktacular** [Recidiviz/covid19-dashboard#208]
**Is your feature request related to a problem? Please describe.**
Part of the UI cleanup
> P1: Delete should move into ‘Edit facility’ view ‘…’ menu

**Describe the solution you'd like**
Move `Delete` button into the `/facility` route. Mocks (XIX 1.2) currently show a `...` menu in _Duplicate Facility_ area, but we have not implemented this area yet.
![image](https://user-images.githubusercontent.com/10144236/80160915-730b5d00-8594-11ea-9bc8-9c147bab0752.png)

**Describe alternatives you've considered**
Design decision

**Additional context**
Do we need to implement the _Duplicate Facility_ feature first? Where should the `...` go if not?

**Comment by jessex** [comment]
I think it's fine to have that menu temporarily only include the delete functionality, personally!

**Comment by cawarren** [comment]
+1 to Josh's comment, I think it's fine if we just add the ... menu at this point, there's a separate issue to bring in 'Duplicate Facility' later.

**Comment by rocktacular** [comment]
ok, where should we put the `...` menu in the current version?
![image](https://user-images.githubusercontent.com/10144236/80231788-7b59ab80-8619-11ea-932e-a32f2fe3fd3e.png)

**Comment by jessex** [comment]
Jen's PR #206 adds a facility description field below the name, which in the mocks is the main component in the section that includes this menu. So we could hold out until that PR is merged and then add it in there?
