### ISSUE TITLE
Add auto-populated locale info on the Add Facility Page

### ISSUE THREAD

**Issue by daschi** [Recidiviz/covid19-dashboard#214]
**What needs to be done? Why does it need to be done?**
Add auto-populated locale info, as shown in mocks 

@jessex  I have a few questions for this feature, let me know if there's someone else I should direct them to. Thanks! 

<img width="760" alt="Screenshot 2020-04-24 12 25 55" src="https://user-images.githubusercontent.com/5402804/80249547-e65daf00-8626-11ea-844c-0af02312fc9a.png">

1. Where can I find the data fields that map to each locale info in the mocks? I've filled out my assumptions here: (from the `localeDataSource` object in the `EpidemicModelContext`) 

      - Population: `totalIncarceratedPopulation`
      - Cases: `reportedCases`
      - Likely Cases: `estimatedIncarceratedCases`
      - Hospital Beds: `hospitalBeds`
      - ICU Beds: ?

2. Is it currently possible in the data model to access these data points without having a facility created yet? I see that in the `EpidemicModelProvider` component we are passing in the `stateCode` and `countyName` for the locale data after a `facility` is set. Should this data also be a part of the scenario?

**Additional context**
Part of #167

**Comment by jessex** [comment]
@daschi the right person to answer that will be either @cawarren, who has been maintaining the dataset that backs the more "static" locale numbers, or @macfarlandian, who knows much more about the epidemic model context than myself.

**Comment by daschi** [comment]
ok thanks! Looking at it more, I think I can start with populating them once a user selects the state & county in the form.

**Comment by macfarlandian** [comment]
FWIW you can access locale data anywhere, there is a single, global `LocaleDataContext` that wraps the entire application. Because it comes from this external datasource, we haven't been persisting it anywhere else to prevent stale data from creeping in. We want to keep it that way unless there's a compelling reason not to.
