### ISSUE TITLE
[Excalibur] Create UI card component for 6 impact metrics related to safety of overall population and reducing r0

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#226]
1. Staff fatalities reduced
2. Staff hospitalizations reduced
3. Incarcerated fatalities reduced
4. Incarcerated hospitalizations reduced

5. hospital beds used 
6. additional staff able to work

PRD section (includes design asset): https://docs.google.com/document/d/1_jbpbsObUWkakyitmuIMaNKhq1YVU_fpo4j06ip8ets/edit?ts=5e95eb62#heading=h.60n6thtiwiid

Mocks: https://www.figma.com/file/6z1QQW84a59Ul3c17PgWdV/%F0%9F%9A%80Recidiviz-CJStatus-(excalibur)?node-id=1476%3A0

**Comment by rocktacular** [comment]
let's make this extensible to do both the 4 `positive impact of releasing...` cards as well as the `positive impact of reducing R0` cards. 

possible props and options:

1. title
2. icon
3. value
4. arrow?
5. subtitle?
6. reduceBy? (the text after the title)
