### ISSUE TITLE
[Excalibur] Display the output chart for a "baseline projection" stacked on top of a "current projection"

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#228]
PRD section: https://docs.google.com/document/d/1_jbpbsObUWkakyitmuIMaNKhq1YVU_fpo4j06ip8ets/edit?ts=5e95eb62#heading=h.ic8dr0xuayy0

Mocks: https://www.figma.com/file/6z1QQW84a59Ul3c17PgWdV/%F0%9F%9A%80Recidiviz-CJStatus-(excalibur)?node-id=1476%3A0

**Comment by daschi** [comment]
I think this might be a duplicate issue with https://github.com/Recidiviz/covid19-dashboard/issues/240 and could be closed now.

**Comment by jessex** [comment]
Looks like a duplicate. Thanks, @daschi
