### ISSUE TITLE
Revisit "unsupported browser" detection code

### ISSUE THREAD

**Issue by szhu** [Recidiviz/covid19-dashboard#230]
**What needs to be done? Why does it need to be done?**

#82 added an "unsupported browser" functionality to detect when a browser ran into issues running the JS, and redirect to an "unsupported browser" page. It was mostly used to detect IE11.
#225 removes the functionality but didn't remove the page.

In this issue, we should decide:
- Whether we want add the "unsupported browser" detection back
- Some examples of old browsers we'd like to target (so we can test it), and what we want the copy to say
- (Briefly) how it should be implemented. For example, if IE11 has partial support, then we should probably bring back the banner approach like in #68 rather than a redirect like in #82.

**Additional context**
https://github.com/Recidiviz/covid19-dashboard/pull/225#discussion_r415396066

**Comment by jessex** [comment]
Thanks for filing this, @szhu! 

Will address this once we've finished testing #225, merged it, and then identified which set of browsers are still not supported. Then I'll sync up with @cawarren about what we want to message at that stage, if anything.

**Comment by jessex** [comment]
Closing this one out. We're happy with browser support as it currently stands!
