### ISSUE TITLE
[Excalibur] - Create New Route and Page Component 

### ISSUE THREAD

**Issue by rocktacular** [Recidiviz/covid19-dashboard#235]
**Is your feature request related to a problem? Please describe.**
Create new route and page for the Excalibur work

**Describe the solution you'd like**
normal new route and page container component

**Describe alternatives you've considered**

**Additional context**

**Comment by rocktacular** [comment]
hmm this is probably a dupe of #233 . Didn't realize @jovergaag had one already. Please close if so.

**Comment by jovergaag** [comment]
Duplicate issue. Addressed in PR #234
