### ISSUE TITLE
[Excalibur] Create bar-chart to display reduction of incarcerated ind.

### ISSUE THREAD

**Issue by rocktacular** [Recidiviz/covid19-dashboard#238]
As per design:
1. show **initial population**
2. show **current population**
3. show `y=C` line - _is this line just the difference?_
4. Hook up to local state/data (might break this out to a separate ticket)

**Comment by daschi** [comment]
Pausing on this due to comment from @sychang 
```
For MVP, it might be a simpler UI treatment to just show the difference in population as a string vs as a bar chart
In later versions, we may be able to hook up real time data to see live population change, which would be better represented as a line graph
```

**Comment by daschi** [comment]
Closing this in place of new issue: https://github.com/Recidiviz/covid19-dashboard/issues/298
