### ISSUE TITLE
Model User and Role Data to Allow for Querying on Multiple Fields

### ISSUE THREAD

**Issue by sprad** [Recidiviz/covid19-dashboard#253]
**Is your feature request related to a problem? Please describe.**
Currently, when we try to use a filter (i.e `where` clause) in combination with an `orderBy` in a Scenario collection query that filters by a user's id (i.e. when we are trying to get a collection of only that user's Scenarios) an error is thrown.

Specifically, if we try to run this query:

```javascript
const scenarioResults = await db
  .collection(scenariosCollectionId)
  .where(`roles.${currrentUserId()}`, "in", ["owner"])
  .orderBy("name")
  .get();
```

We receive the following error:

`FirebaseError: The query requires an index. You can create it here: https://console.fire...`

In order to be able to run this query, Firestore must create a [composite index](https://firebase.google.com/docs/firestore/query-data/index-overview#queries_supported_by_composite_indexes) to look up this data.  Generally, this isn't a huge issue as creating a composite index on multiple fields is straightforward.  However, as it stands we've modeled our data such that the `roles` defined within a Scenario collection dynamically create a field of the user's Auth0 id which points to an array of that user's roles.  Example:

<img width="577" alt="Screen Shot 2020-04-29 at 12 20 48 PM" src="https://user-images.githubusercontent.com/25503/80621525-6adc7300-8a15-11ea-8fae-4e4b727ede00.png">

This has worked fine for our existing use cases but is now problematic if we want to query on multiple fields.  Technically, we can fix this issue by creating a composite index on the dynamic field user id filed and the `name` field as follows:

<img width="963" alt="Screen Shot 2020-04-29 at 12 17 22 PM" src="https://user-images.githubusercontent.com/25503/80621909-01109900-8a16-11ea-97ec-a4dbb7f246ba.png">

But we would have to do this programmatically every time a new user is created.  This is a non-starter for two reasons:  1).  These indexes take several minutes to create and 2). We are limited to only creating 200 of these indexes.  The latter is problematic in particular because it would cap our user base at 200 and wouldn't allow for the creation of other composite indexes to support other use cases.

**Describe the solution you'd like**

More research will need to be conducted, but I believe the solution is to remodel our data such that the Scenario's `roles` map is made up of static field names.  Something like:

```javascript
roles: {
  owners: [user id1]
  viewers: [userid2, userid3]
}
```

This would allow us to create a one-time composite indexes on `scenario.name + scenario.roles.owners` and `scenario.name + scenario.roles.viewers`.

**Note:**  This would require a data migration of our existing data.

**Comment by jessex** [comment]
Thanks a lot for identifying this, @sprad! This will be a blocker for any feature that relies on querying by a given user, which would include at least facility sharing. I think your solution is the right one and I recognize this requires some ability to perform a migration. Fortunately, this is only at the scenario level which is a lot simpler, so in a pinch we could do a manual migration. But regardless, the fact that this is still shared between tiers means that we'll likely need to bake in some temporary flexibility in how we parse `roles`.

**Comment by jessex** [comment]
Oooh I looked close at this query after reading your PR for #256. This only comes into play, in this instance, because of the existence of the `orderBy` clause, right? So potentially other query patterns could also become blocked on this issue, but this particular instance would not block further development on, e.g. facility sharing, because we can move the order to memory. Right?

**Comment by sprad** [comment]
That's right.  Without the `orderBy` clause in the Firestore query we can still get the filtered data we need (i.e. the scenarios for a given user) and then manually sort the returned data in memory using Lodash's `sortBy`.  At the moment, there aren't any downstream effects and we can carry on with other _multi-facility_ related work.

I'm somewhat skeptical that our current model will hold up and play nicely in the _facility sharing_ world, but that still needs to be researched.  We'll likely need to give some thought to how to model the sharing of facilities with respect to users and roles since, as we see here, if we don't get it "right", it can be pretty challenging to unravel the mistake.

**Comment by jessex** [comment]
Now that we are sharing scenarios, duplicating facilities, and all that fun stuff, do you think there's anything still needed here, @sprad?

**Comment by sprad** [comment]
@jessex - Since we've more or less doubled-down on our current model at this point, this issue isn't likely worth pursuing so I'll close it.  We can continue to do more complicated sorting (and even filtering) in memory if necessary since we aren't typically dealing with too much data.
