### ISSUE TITLE
R(t) Calc - handle multiple observations on same day

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/covid19-dashboard#254]
When this happens we will want to order or filter by this secondary field (confirmation on that TBD, based on calc function requirements)

Likely need to add a composite index for "observedAt" and "updatedAt" fields in Firestore for querying/ordering multiple versions on the same day. 

We are currently doing the filtering post-fetch on the client side by ordering the fetched records as part of the `getRtInputsForFacility` function, as it is required to prevent errors from our Rt calculation function. Once we can perform this ordering and filtering in the database itself, the database function (currently named `getFacilityModelVersions`, though that should probably changed) should be updated to issue a query that returns just one record per day (the most recently updated one) and all of the client-side uniqueness and ordering code in `getRtInputsForFacility` should be removed.

See discussion at https://github.com/Recidiviz/covid19-dashboard/commit/191e4b09ad699b7941fa012b94b1ab9e58362085#r38825212

**Comment by SoumyaMahadevan** [comment]
Instruction/steps [here](https://docs.google.com/document/d/1bmwoPdAVCR4hrP-4YVtp2Nrc6CN-7muDU-P_hwUPKV0/edit?usp=sharing)

**Comment by SoumyaMahadevan** [comment]
- Created a new project and new app and imported the data from the existing project.
- Tested the composite index by querying for two fields in getFacilityModelVersions:
diff --git a/src/database/index.tsx b/src/database/index.tsx
index 92bbd4b..c34a8f6 100644
--- a/src/database/index.tsx
+++ b/src/database/index.tsx
@@ -304,6 +304,7 @@ export const getFacilityModelVersions = async ({
       .doc(facilityId)
       .collection(modelVersionCollectionId)
       .orderBy("observedAt", "asc")
+      .orderBy("updatedAt", "desc")
       .get();

     return historyResults.docs.map((doc) => {

- Verified getRtInputsForFacility's o/p is the same before and after removing the extraneous orderBy:
diff --git a/src/infection-model/rt.tsx b/src/infection-model/rt.tsx
index 5f04e3f..8279048 100644
--- a/src/infection-model/rt.tsx
+++ b/src/infection-model/rt.tsx
@@ -83,16 +83,8 @@ const getRtInputsForFacility = async (

   // inputs must contain no more than one record per day.
   // when we have multiples, filter out all but the most recently updated
-  // TODO: it may be possible to do this filtering directly in the query
-  // with a compound index, see #254 and replace this code if possible
   modelVersions = uniqBy(
-    orderBy(
-      modelVersions,
-      ["observedAt", "updatedAt"],
-      // uniqBy retains only the first item when it encounters duplicates,
-      // so make sure the most recently updated one is first
-      ["asc", "desc"],
-    ),
+    modelVersions,
     // make sure time doesn't enter into the uniqueness
     (record) => record.observedAt.toDateString(),
   );

- No errors in console related to the index.

**Comment by SoumyaMahadevan** [comment]
Steps remaining in the setup of the new project:

- Add Auth integrations
- Add the python functions

**Comment by jessex** [comment]
Thanks, @SoumyaMahadevan! Having this documentation will be very helpful to introduce a staging tier of Firebase in the hopefully near future.

As regards the purpose of this ticket, @macfarlandian, do you have any questions or concerns based on the testing that Soumya documented? If not, and you think we're free to proceed with creating the index in production (I feel good about it myself), then can you update the issue description with exactly what we want to do in code? Is it just making the updates on the TODOs that Soumya documented, or anything more?

**Comment by macfarlandian** [comment]
yeah this sounds great to me! I don't think there is anything else needed to satisfy this ticket.

**Comment by SoumyaMahadevan** [comment]
Thanks @macfarlandian and @jessex . Creating the composite index on prod now, will send out the PR once that is completed and tested.

**Comment by macfarlandian** [comment]
@SoumyaMahadevan I updated the description just to make it clear that all the filtering should be done in the query - eliminating the need for calling `uniqBy` in `getRtInputsForFacility` as well

**Comment by SoumyaMahadevan** [comment]
@macfarlandian I don't see an easy way to do a distinct on the firebase query. The collections api doesn't support distinct/groupBy etc. - see https://firebase.google.com/docs/reference/js/firebase.firestore.CollectionReference. So I think `uniqBy` is the way to go, while removing `orderBy` in `getRtInputsForFacility`

**Comment by macfarlandian** [comment]
oh that's too bad .... ok well I guess we leave that bit in
