### ISSUE TITLE
Populate Domain Objects with Consistent Types

### ISSUE THREAD

**Issue by sprad** [Recidiviz/covid19-dashboard#262]
**Is your feature request related to a problem? Please describe.**

We currently manage dates and times inconsistently in Firestore and in our code.  Specifically, we are storing automatically managed dates (i.e. `createdAt`, `updatedAt`, etc.) as Firestore Timestamps, but we are storing user input values (i.e. Planned Release dates) as strings.

This creates issues for client code interacting with data returned from Firestore because it must know how to deal with these different data types.  This leads to inconsistent, confusing, and buggy code.

**Describe the solution you'd like**

A better solution would be to populate our domain objects (i.e. `Facility`, `Scenario`, `PlannedRelease`, etc.) with specific types so that client code can easily know about and interact with data in a consistent manner.  At the moment, this mostly applies to Date like objects.  See the conversation [here](https://github.com/Recidiviz/covid19-dashboard/pull/245/files#discussion_r417629653) for a list of the current fields we need to explicitly manage.

**Note:**  This solution should be implemented such that we do not have to do any manual data migrations.  This means that the code to populate Date objects will need to be able to handle either Strings or Firestore Timestamps.

**Describe alternatives you've considered**

Firestore does have a mechanism for returning its Timestamps as dates, but this is a deprecated approach that will break our code when Google releases the next version of Firestore "soon."  For more details see [this conversation](https://github.com/Recidiviz/covid19-dashboard/pull/245/files#r417727550).

**Comment by szhu** [comment]
@sprad just checking, this is closed by the PR, right?

**Comment by sprad** [comment]
@szhu - Yup!  It's done
