### ISSUE TITLE
Refactor PrivateRoute to not contain Route

### ISSUE THREAD

**Issue by jessex** [Recidiviz/covid19-dashboard#27]
**What needs to be done? Why does it need to be done?**
As suggested in https://github.com/Recidiviz/covid19-dashboard/pull/26#discussion_r404453326, we should consider migrating `PrivateRoute` from a component to a hook, for cleaner separation of concerns.

**Additional context**
`PrivateRoute` was copied wholesale from Auth0 documentation in #26.

**Comment by szhu** [comment]
#81 closes this with its "Move Route out of PrivateRoute" commit.
