### ISSUE TITLE
[Excalibur] Population assumption tooltip

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/covid19-dashboard#287]
**What needs to be done? Why does it need to be done?**
Add a tooltip to the top of the page (clearly visible) explaining where our original projection population assumptions come from. This would prompt them to model all their other facilities or talk to us if they have issues to our assumption so we can adjust for future versions.

Copy to be provided by @sychang 

**Additional context**
This is for MVP. Follow up issue will give them a way to manually set their original projection population.

**Comment by sychang** [comment]
This may be made obsolete by #296
