### ISSUE TITLE
R(t) Timeseries: don't plot 0.0 value that always appears on the first day

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/covid19-dashboard#292]
currently the first day's value returned from the Rt function is not really "valid" since the values are based on difference from the previous day, and there is no previous day. The best solution is probably to simply not return this value from the function; confirm this approach with PM/DS  before proceeding

**Comment by justkunz** [comment]
I would recommend updating [this line](https://github.com/Recidiviz/covid19-dashboard/blob/master/backend/python-functions/realtime_rt.py#L139) to drop the first row (row 0)
```result = pd.concat([most_likely, hdis], axis=1).iloc[1:]```

And when this change goes in I would also like to request an additional line to drop any duplicate case counts, which can be done after L118 before L122:
```case_df = case_df.drop_duplicates(keep='first')```
This would help smooth out some of the big drops we see when a user enters the same case count for multiple days in a row. We believe these duplicate case counts are usually an artifact of little or no testing, and not a sign that the virus has actually been contained.
