### ISSUE TITLE
R(t) - Add new promo for Rt

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#303]
**Is your feature request related to a problem? Please describe.**
We've just added the Rt chart, but it's not very discoverable.

**Describe the solution you'd like**
Add a new promo in Merlin that has a higher priority than the other promos. The copy should read:

> New! View the chart of Rt (the rate of spread over time) for any facility by selecting it. This is based on the number of cases over time for that facility. To get an accurate Rt, enter case counts for previous days by clicking the number of cases on the right (in red) to update case numbers.)

**Describe alternatives you've considered**
TBD

**Additional context**
The promo should otherwise be consistent with all other promos in terms of dismissal behavior, etc.

**Comment by jessex** [comment]
If we're going to add a tab that has a large rate of spread chart for all facilities this week, is the promo still necessary?
