### ISSUE TITLE
R(t) - UI improvements to 'Add cases' modal

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#305]
**Is your feature request related to a problem? Please describe.**
The **Add cases** modal is overwhelming, with how many input boxes it has. This discourages users from entering historical case information, or updating cases daily.

**Describe the solution you'd like**
- Change copy on the 'Unknown Age' row to 'Facility Residents', and the second column in it to 'Resident population'
- Hide all of the other age breakout inputs under a collapsible section
- If the user expands that collapsible section, clear and disable the Facility Residents row

**Describe alternatives you've considered**
TBD

**Additional context**
This is part of the 5/3 UI polish round.

![image](https://user-images.githubusercontent.com/59526/80984446-dc446900-8dfb-11ea-9d96-3c8a97f628f4.png)

**Comment by jessex** [comment]
@cawarren , I fear that this will be a bit confusing to users who won't know that "facility residents" is equal to "age unknown." Why not keep the labels the same but just hide the rest in a collapsible menu?

**Comment by cawarren** [comment]
Sorry for missing this. I'm worried this will be confusing if someone just reads the labels on the left - I have staff, and then I have ages unknown (Is that still staff? Where do I put the incarcerated population?)

It's a tricky bind here - I'd suggest changing the label to 'Resident population', but then when they expand they're going to expect this row to be the sum of all of the rows below it (when it isn't, it's a bucket for anything that doesn't fall into those other rows).

Here's another option, I'm not sure it's any easier though:
- We could also make it 'Facility residents', and it is the sum of the rows below. In that case the 'Unknown Ages' bucket is _not_ editable, and just absorbs the difference between the rows below and the 'Facility residents' field above (which is now a total pop field). If we do that, it could continue to work that way even when collapsed and the user just wouldn't see that all the people they're entering are going into Unknown Ages.
