### ISSUE TITLE
Merlin UI polish (Rt Edition)

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#306]
**Is your feature request related to a problem? Please describe.**
Another week, and we've done an incredible amount of feature development. After the Rt launch, it's now time to take a quick step back and polish some parts of the UI that have gotten a little out of step with the mocks (or where the mocks had a good idea that didn't pan out).

**Describe the solution you'd like**
Please take a look at [this document](https://docs.google.com/document/d/1pP75jvFXZVSImCLFgvcw7nxSYnKC4nbob_tewAfuZpY/edit), 
- Claim an item from the list
- Make a sub-issue that refers back to this one that you can work in on that item
- Put your name and issue number next to the item in the list so that others know you're working on it

**Additional context**
- [Mocks](https://www.figma.com/file/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=910%3A130)
- [Copy doc](https://docs.google.com/spreadsheets/d/1bnBsQXbtrRogruVkDPiAketsHUrv3H26ibw0ydh94D8/edit#gid=1594361286)

**Comment by rememberlenny** [comment]
Picking up this task.

**Comment by jessex** [comment]
Every sub-task has been completed and deployed to production. Closing this out!
