### ISSUE TITLE
Users can enter cases without population, resulting in negative charts

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#314]
**Describe the bug**
Entering cases for the incarcerated population that exceeds the total population results in peculiar chart behavior. See attached screenshot.

**To Reproduce**

1. Go to 'Add Facilities'
2. Click on Ages Unknown, Current Cases
3. Enter 200
4. See chart

**Expected behavior**
Should highlight red the case numbers box in red if it exceeds the total population number (for both staff and pop).

**Screenshots**
![image](https://user-images.githubusercontent.com/59526/81027162-a11d5680-8e4a-11ea-863c-36a93a163657.png)

**Comment by jessex** [comment]
Just added this to TODO, @cawarren. Feel free to prioritize as you see fit.

**Comment by cawarren** [comment]
Thanks Josh

**Comment by glen0071** [comment]
@jessex, please direct me to best answerer for this question.

Seems like this can be handled by checking if new `value` or (`model[leftKey]`) is greater than `model[rightKey]`. Any example in the codebase you can direct me to about dynamically setting styles on a element/component? 

I'm used to setting dynamic classNames like `className={'container ' + variable}` or something. But I'm not sure how that works with `styled-componenents`. Any hints?

**Comment by jessex** [comment]
@macfarlandian can you provide @glen0071 with a relevant example for what he's trying to do here? Thanks much!

**Comment by macfarlandian** [comment]
@glen0071 you can use `className` the same way on a styled component, and use those classes in the styled-component's definition. e.g., https://github.com/Recidiviz/covid19-dashboard/blob/master/src/page-multi-facility/RateOfSpreadPanel.tsx#L26

it supports a nesting syntax that is basically the same as SCSS, which allows you to target classes set on the element itself and not just its descendents, as in that example.
