### ISSUE TITLE
Fix unresponsive data reports and data sharing toggles

### ISSUE THREAD

**Issue by jessex** [Recidiviz/covid19-dashboard#317]
**Describe the bug**
The toggles for turning data reports and data sharing on and off are no longer responsive in master. They still work as expected in production.

**To Reproduce**

1. Go to the scenario details page
2. Click on the data reports or the data sharing toggles on the side menu
3. See that they do not respond visibly and also do not update any state, as they remain the same on page refresh

**Expected behavior**
Toggling these should update state as expected and should be visible immediately.

**Desktop (please complete the following information):**

- OS [e.g. Windows 10]: All
- Browser [e.g. chrome, edge]: All
- Version [e.g. 22]: All

**Additional context**
This is a regression since the most recent release to production.

**Comment by macfarlandian** [comment]
assigning this to @rememberlenny for bean-counting purposes because I am 99% sure it's the same issue as #309
