### ISSUE TITLE
[Merlin] Exclude hospital beds when setting y-axis max on output chart

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#338]
**Is your feature request related to a problem? Please describe.**
We currently set the y-axis max value by the largest of all of the factors (hospital beds, cases, etc.) Unfortunately, many people don't set the state and county up and so the hospital beds tends to pull the y-axis super high (if they leave it set to a state, or the country as a whole).

**Describe the solution you'd like**
We should let hospital beds fall where they may, and not include them in deciding where to set the max y-axis. (This may be more difficult than I expect in implementation if the library handles this automatically under the hood).

The way I'm hoping this might work is that:
- The max y-axis is set by the tallest curve, not by hospital beds
- If the hospital beds from the current selection happen to fall within the view of the chart given that y-axis range, then great - they'll be visible to the user
- If the hospital beds from the current selection do **not** fall into the view of the chart given the y-axis range, no worries - they're simply not visible to the user.

**Describe alternatives you've considered**
We could also remove hospital beds altogether, if this is too complex given how the charting lib works.

**Additional context**
Add any other context about the feature request here.

**Comment by jessex** [comment]
Just to confirm, @cawarren, this is for both the facility details and the excalibur impact report graphs, right? The facility rows in the scenario details page no longer show the hospital beds line so it's irrelevant there.

**Comment by cawarren** [comment]
Confirmed w/ @sychang this should be on both Facility Details and Excalibur.

Also I still see hospital beds on Scenario Details - has that change just not made it to prod yet?

**Comment by jessex** [comment]
Yep! Sorry for the confusion. It's in staging but not production. It will go into prod tomorrow at the latest. If you'd like it to go to prod right now, I'm happy to do another release (that release would also include the typo fix from the Rt promo).

**Comment by cawarren** [comment]
Not urgent enough to eat into your time now vs. in the morning, imo - great to hear that's going away though!
