### ISSUE TITLE
Fix inconsistent Rt pill coloring in corner case

### ISSUE THREAD

**Issue by jessex** [Recidiviz/covid19-dashboard#345]
**Describe the bug**
The Rt pills in the top-right corners of the epidemic curve graphs in the facility rows of the scenario details page round the Rt value off to a single decimal point for display purposes. However, the color of the pill is determined by the non-rounded value of Rt. In particular, it is possible to have a pill displaying 1.0 with a value of, say, 0.95, and another displaying 1.0 with a value of, say, 1.03, and though they will both read as 1.0 they will have different colors.

See the screenshot below.

**To Reproduce**

1. Generate a facility with observation dates that has an Rt that is just below 1.0
2. Generate another with an Rt just above 1.0
3. Observe that their displayed values are the same but their colors are different

**Expected behavior**
We could either:
1. Change the colors to be toggled based on the displayed/rounded value - this sacrifices precision for consistency and simplicity
1. Change the display to include an extra decimal place, which would limit the potential for this happening by roughly an order of magnitude (you'd need to have a facility that is >0.99 and another that is <1.01) - this maintains precision and simplicity but can still lead to inconsistency, though less often
1. Maintain the status quo and accept that this issue is fairly uncommon

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

<img width="57" alt="Screen Shot 2020-05-07 at 22 15 43" src="https://user-images.githubusercontent.com/431895/81369829-b8f61400-90b0-11ea-9d86-aba97ca11fc0.png">

**Comment by jessex** [comment]
@sychang can you weigh in on what solution you'd like here?

**Comment by sychang** [comment]
All things equal, I'd go with option 2 because it matches the precision-level on the "rate of spread" tab (in this screenshot below, it says 0.51 on the rate of spread tab and 0.5 on the facility library page so this would make the two consistent.

![image](https://user-images.githubusercontent.com/6633887/82972440-ac235c80-9f9a-11ea-893d-b3400d94837f.png)

**Comment by jessex** [comment]
In short, @kattak, the R(t) calculation is quite complex. I can't really give a narrative description of how to recreate those cases. The simplest path is that you would need to keep adding new historical case counts to a given facility until you got to the number you wanted to test. You could also push up a pull request when you got to a point that you thought was the right, ready solution, and ask others to test with their own data.
