### ISSUE TITLE
Enhance the Data Visualization in the Scenario Library

### ISSUE THREAD

**Issue by sprad** [Recidiviz/covid19-dashboard#347]
**Is your feature request related to a problem? Please describe.**

At the moment, our Scenario Library modal shows each Scenario with a simple data visualization that includes the Recidiviz logo (see the image below).  Ideally, we would provide something more visually appealing.  The [original mocks](https://www.figma.com/file/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=910%3A130) show a data visualization that represents the projection graph of the first facility within the scenario.

<img width="1678" alt="Screen Shot 2020-05-08 at 12 38 36 PM" src="https://user-images.githubusercontent.com/25503/81437278-e8e8fa00-9138-11ea-86d8-566ffea79d87.png">

**Describe the solution you'd like**

Part of the solution is to figure out what the ultimate solution is and to decide if this is something we even want to pursues.  At the moment, here are a few options and some of their advantages and disadvantages:

1.  Leave the Recidiviz Logo visualization in place.
- Pros:
  - The work is already done
  - There aren't any performance implications
  - The case where a scenario does not yet have any facilities is already handled
- Cons:
  - Visually boring

2.  Implement the ideal visualization as defined in the mocks:
- Pros:
  - Looks good
  - Is somewhat relevant to the underlying Scenario
- Cons:
  - Will require additional database code (or updates) to allow for fetching a single facility
  - Will likely have performance implications due to additional data fetching and chart rendering
  - May require untangling some code since at the moment `useModel` (where we translate `modelInputs` into projection curves) must be used within an `EpidemicModelContext` which relies on a `LocaleDataSource`.  Coupling all of these things into this Scenario Library experience seems awkward from a code perspective.
  - Still need to handle the case where a scenario doesn't yet have any facilities

3.  Generate Random Graphs.  I have this semi-working in a local branch on my machine.
- Pros:
  - Looks good
  - Probably easier to implement than Option 2
  - The case where a scenario does not yet have any facilities is handled
- Cons:
  - Could be difficult to implement realistic looking curves
  - Might have to be smart about the curve generation such that generated curves are static for a given scenario.  Otherwise it might be confusing if the curves are constantly changing for the same scenario.

**Comment by jessex** [comment]
Thanks for the write-up, @sprad! Interested in thoughts from @cawarren here. Another con to add to option 3 is that it would be misleading, as users will naturally assume these are real graphs representing a given scenario--they may even take screenshots of that view itself to send to colleagues as a quick visualizer of the different scenarios. I think that option is likely a non-startere.

**Comment by cawarren** [comment]
Adding this into the polish round (#534) - I think Option 2 is the best option here, all things considered.
