### ISSUE TITLE
Properly Handle Scenario Change State Management

### ISSUE THREAD

**Issue by sprad** [Recidiviz/covid19-dashboard#348]
**Describe the bug**

When selecting a scenario within the Scenario library most of the application resets to use the new scenario's information, but the Name and Description in the Scenario Sidebar do not.

**To Reproduce**

0.  Make sure you have created at least two scenarios
1. From the home screen notice the name, description, toggles, facilities, etc. for the Scenario you are concurrently viewing.
2. Click on the Scenario Library folder and select a different scenario from the one that you are currently viewing.
3. Notice that the Scenario sidebar updates correctly for the toggles and last updated at date.  Also notice that the facilities associated with the clicked on scenario are also loaded.  However, notice that the Scenario's name and description in the sidebar are not updated to reflect the currently viewed scenario's information.

**Example**

Viewing my baseline scenario:

<img width="1363" alt="Screen Shot 2020-05-08 at 2 41 14 PM" src="https://user-images.githubusercontent.com/25503/81438419-bb04b500-913a-11ea-9b83-3e071b6590b1.png">

Switching to another (non-baseline) scenario

<img width="1334" alt="Screen Shot 2020-05-08 at 2 41 23 PM" src="https://user-images.githubusercontent.com/25503/81438467-d243a280-913a-11ea-9169-1e33c9d2c55c.png">

Again, notice that all of the expected facilities and attributes in the sidebar are loaded as expected except the name and description.  Note:  The updated date happens to be the same in both scenarios, but I've confirmed that this value does change when navigating through scenarios with different updated dates.

**Comment by jessex** [comment]
I would consider this one a release-blocker for multi-scenario. CC @cawarren
