### ISSUE TITLE
[Excalibur] UI Updates for the population modal

### ISSUE THREAD

**Issue by daschi** [Recidiviz/covid19-dashboard#349]
**What needs to be done? Why does it need to be done?**

- ~Update the copy on the two modal pages~
- ~Add the tooltips next to the form labels~
- ~Change default starting date to 2/1/2020~
- ~add baselinePopulations property to duplicate scenario function~
- ~Edit: When only 1 facility is modelled, update copy for the title and body (2 instances) to say "1 facility" instead of "1 facility"~
![image](https://user-images.githubusercontent.com/6633887/81450169-81867680-9147-11ea-9ab9-6e93b8f30f69.png)

https://www.figma.com/file/6z1QQW84a59Ul3c17PgWdV/%F0%9F%9A%80Recidiviz-CJStatus-(excalibur)?node-id=1837%3A494

**Additional context**
Updated mocks:
![image](https://user-images.githubusercontent.com/6633887/81441214-fc936100-9136-11ea-977a-0f2617cca37b.png)

![image](https://user-images.githubusercontent.com/6633887/81441237-061cc900-9137-11ea-96a6-3fae431ef9e9.png)

Tooltip text:
- Date: "To model the impact since the start of COVID-19, enter a date prior to any COVID-19 mitigation efforts."
- Total incarcerated population: "Enter the total incarcerated population across all modelled facilities at the selected date."
- Total staff: "Enter the total staff population across all modelled facilities at the selected date."

**Comment by jessex** [comment]
Is this release blocking for Excalibur, @sychang? 

Regardless, let's move it into the TODO column at the right priority when you've got a chance.

**Comment by sychang** [comment]
Yes it is, just chatted with @daschi about it, who will look at it this afternoon. Will move now.
