### ISSUE TITLE
Remove Icon Coupling from the InputNameWithIcon Component

### ISSUE THREAD

**Issue by sprad** [Recidiviz/covid19-dashboard#350]
**Describe the bug**
Our current `InputNameWithIcon` [bakes in a toggle](https://github.com/Recidiviz/covid19-dashboard/blob/master/src/design-system/InputNameWithIcon.tsx#L61) to display a folder icon when the passed in `showIcon` property is set to true.  This creates an issue for the new scenario library because the intention of this icon is to be used as a trigger for presenting the Scenario Library modal.  It doesn't make sense to put the Scenario Modal loading code in this otherwise generic component.

**To Reproduce**

N/A - mostly a code refactoring

**Expected behavior**

Rename the `InputNameWithIcon` to `InputName` and remove its functionality to show or hide the folder icon.  This will make the component itself more generic and will also give it parity with its sister `InputDescription` component.  After that refactor, separately include the folder icon in the Scenario Sidebar and add a click handler to it that triggers the display of the Scenario Library Modal.

**Screenshots**

The folder icon highlighted in red below should no longer be tied to the `InputNameWithIcon` and should instead exist independently such that it can trigger the Scenario Library modal when clicked:

<img width="386" alt="Screen Shot 2020-05-08 at 3 04 01 PM" src="https://user-images.githubusercontent.com/25503/81440040-69a9f500-913d-11ea-85e7-b7911e341d75.png">

**Comment by jessex** [comment]
Does this actually impact functionality, @sprad, or is it just tech debt?

**Comment by sprad** [comment]
I believe you could get things to work without impacting any user-facing functionality, but you'd have to do some pretty hacky stuff to do so.  Like, include very use case specific code within an otherwise generic component.

**Comment by jessex** [comment]
But I guess I don't understand from first read what the issue _is_. Is it that you can't click this to load the scenario library? Is it that once inside the library modal it breaks something?

**Comment by sprad** [comment]
Yeah, sorry it's a little hard to explain in a concise way so I'm sure the write up is a bit confusing.  The issue is this:

- We want to trigger the Scenario Library Modal to open when a user clicks on the Folder icon next to the scenario's name in the sidebar.
- For whatever reason, that icon lives within the `InputNameWithIcon` component in our design-system and is shown whenever we[ pass in a boolean property](https://github.com/Recidiviz/covid19-dashboard/blob/master/src/design-system/InputNameWithIcon.tsx#L61) called `showIcon`.
- The way our modals work is that they wrap a triggering component [like this](https://github.com/Recidiviz/covid19-dashboard/blob/4d9b6032178fb002f923d1015c411179108245e9/src/page-multi-facility/FacilityRow.tsx#L140-L154) (Note the `trigger` property is itself a component).
- To follow along with this pattern, I'd need to pass in a similar `trigger` component to the Scenario Library, in this case, the folder icon, but as stated above this icon is nested within the `InputNameWithIcon`.  Visually in code, the problem looks like this:

<img width="630" alt="Screen Shot 2020-05-08 at 4 12 11 PM" src="https://user-images.githubusercontent.com/25503/81445960-ed68df00-9147-11ea-87b4-35b7986062e0.png">

I need the `ScenarioLibrary` trigger component to be the `IconFolder` as shown by the red arrow, but that icon is embedded within the `InputNameWithIcon` component.

At any rate, I've come up with a solution in this PR:  #363
