### ISSUE TITLE
Merlin UX: Rt z-index is above modal dialogs

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#355]
**Describe the bug**
The Rt on the Scenario Details page (the pill per row) is beautiful, but continues to shine through even as the user opens the Case Updates modal.

**To Reproduce**
- Open Scenario Details
- Click one of the red Case numbers

**Expected behavior**
We should adjust the z-index (or implementation details of your choice) to move these a bit lower in priority so they stay behind modals (plural, since the Multi-Facility modal will land soon).

**Screenshots**
![image](https://user-images.githubusercontent.com/59526/81449069-6dde0e80-914d-11ea-9f78-be682eca2d23.png)
**Desktop (please complete the following information):**

- OS: Ubuntu 18.04
- Browser: Chrome
- Version: 81.0.4044.138

**Comment by amyrlam** [comment]
I think @rememberlenny got this in https://github.com/Recidiviz/covid19-dashboard/pull/409
