### ISSUE TITLE
Merlin - 5/11 Fit 'n finish polish round 

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#372]
**Is your feature request related to a problem? Please describe.**
Several minor polish issues to re-align with mocks.

**Describe the solution you'd like**
Please
- Identify an issue from [the doc](https://docs.google.com/document/d/15oREP0hXoQSnzL-mMp3fTYRLyomyhskLD38-l2t1v_E/edit)
- Put your name next to it in the doc
- File an issue referring back to this one to work out of
- Cross off the item in the doc when you're done

If you have any questions at all, ping @cawarren or @sychang 

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by sychang** [comment]
Moved issue back to "To Do" so other folks can continue hoping into the doc and grabbing issues

**Comment by amyrlam** [comment]
@sychang ah makes sense now, my bad!

**Comment by amyrlam** [comment]
I worked on a couple things in the Google Doc. For clarity, subtasks of this issue are open to anyone and I'll assign myself to something in the Google Doc if move back to this!

**Comment by amyrlam** [comment]
Took a new task from the Google Doc
