### ISSUE TITLE
Remove 'Daily Report' and 'Data Share' toggles

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#373]
**Is your feature request related to a problem? Please describe.**
After a bunch of user feedback and UXR, we've found the two toggles on the left-hand side are more confusing than helpful at this point. We'd like to remove them from the UI prior to an e-mail announcement about Rt features.

**Describe the solution you'd like**
Please remove these toggles from the UI, or hide them if full removal is more involved.

**Describe alternatives you've considered**
Several options were discussed last week for adjusting these, but unfortunately removal is cleanest for now. It's possible that we'll reuse the UI styling for the toggles for other features in the future.

**Comment by jessex** [comment]
Does this mean we also need to remove the possible display of their related promos? I presume it does. CC @cawarren

**Comment by cawarren** [comment]
Yes, thank you!
