### ISSUE TITLE
Viewing historical case data on the facility detail page

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#404]
**Is your feature request related to a problem? Please describe.**
Currently, users have no way of viewing the historical case and population data they have entered for a facility. This causes problems because it is difficult to debug a faulty R(t) and hard to know where they are missing data. We also want to encourage them to give us a complete set of data so we can give them the most accurate projection.

**Describe the solution you'd like**
Because they add cases on a per-facility level, we want to add a chart that allows them to view the case data they have inputted historically and easily identify where they are missing data.

![image](https://user-images.githubusercontent.com/6633887/81773381-c3981b00-94ad-11ea-9e79-a442cf68ca9c.png)

![image](https://user-images.githubusercontent.com/6633887/81773410-cdba1980-94ad-11ea-93aa-928e97e8a907.png)

Components

1. Bar chart by default shows the most recent 30 days. 
2. Clicking “Previous 15 days” scrolls the chart to be able to show the previous 15 days of data (if there is an easier chart library to handle scrolling back in time, feel free to use that)
3. Each bar is a click target that opens the “add historical data” modal with the date of the bar pre-selected
4. When there’s no data, the bar is red and stretches the full y-axis length of the chart (On click, opens the “Add historical data” modal with the date pre-selected to the date of the bar. On hover, color gets darker to show that the bar is a click target. Clicking on the hover text should also open the modal)
5. When there is data for a day, the bar is green and has a height of the # of confirmed cases (On click, opens the “Add historical data” modal with the date pre-selected to the date of the bar, with data pre-populated from what the user previously entered). On hover, shows the date, case count, and a CTA to click to change the case count. Click on the hover text should also open the modal)
6. P2: If a case count is 0 or less than 50% between the first y-axis line and 0, display the count above the bar
7. Button at the top right “+ Add Historical Data” to open the “add historical data” modal with yesterday’s date pre-selected (or the default we are currently using)

Mocks: https://www.figma.com/file/6z1QQW84a59Ul3c17PgWdV/%F0%9F%9A%80Recidiviz-CJStatus-(excalibur)?node-id=2206%3A6804

**Describe alternatives you've considered**
We considered showing a table or calendar widget that indicates historical data and data missing. A bar chart lets them see the trend over time. A line chart was also considered, but it is more challenging to interact with.

**Additional context**
This information is repeated in this doc, in case there are complications that warrant a longer discussion: https://docs.google.com/document/d/1KRCYPeC3W7KJm7flUpZKPxdhL7U0sRTfisD0cjqQYuM/edit#heading=h.xr8mpbcylhxh

Related to #405

**Comment by jessex** [comment]
Mocks look fantastic, @sychang. Clarification: for number 5, if you click on a green bar and open the modal, should it also be pre-populated with the latest inputs entered for that date?

**Comment by rememberlenny** [comment]
@sychang @jessex Any thoughts around having an optional table as well?

**Comment by jessex** [comment]
Sorry, what do you mean by that, @rememberlenny? Can you be more specific?

**Comment by rememberlenny** [comment]
Logging here that @sychang and I spoke about this. In summary, displaying the added case data as a table would help. Each row would be a day of data.

**Comment by rememberlenny** [comment]
Just to note, the table is a separate feature from the chart and isn't relevant here for the time being.

**Comment by sychang** [comment]
After discussing with more folks, the table is separate from this particular issue (and not an entirely feasible solution) so I'll delete the pieces of this thread to minimize confusion.

**Comment by sychang** [comment]
Yes, if you click the green bar, it should be pre-populated with the latest inputs from that date. Will clarify in the original comment.

**Comment by daschi** [comment]
@sychang Just want to confirm that each bar should be the total cases for both incarcerated and staff

**Comment by sychang** [comment]
Sorry for the delay - both staff and incarcerated combined!
