### ISSUE TITLE
Viewing historical population data over time on the facility detail page

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#405]
**Is your feature request related to a problem? Please describe.**
Currently, users have no way of viewing the historical case and population data they have entered for a facility. We want to encourage users to enter accurate historical population data because if we have their per-facility historical population data, we will be able to run Excalibur on a per-facility basis.

**Describe the solution you'd like**
This is an addition to letting users see the historical case counts, we want them to be able to see the population data they have inputted over time on the facility detail page.

![image](https://user-images.githubusercontent.com/6633887/81773666-75374c00-94ae-11ea-89fe-7c3e93377910.png)

![image](https://user-images.githubusercontent.com/6633887/81773681-7a949680-94ae-11ea-9ba9-b3e4da74c99b.png)

Components

1. Users by default see case and population data overlaid on top of one another. They can turn off the case data to just view the population data and vice versa.
2. Bar chart by default shows the most recent 30 days-worth of data. 
3. Clicking “Previous 15 days” scrolls the chart to be able to show the previous 15 days of data (if there is an easier chart library to handle scrolling back in time, feel free to use that)
4. Each bar is a click target that opens the “add historical data” modal with the date of the bar pre-selected
5. When there’s no data, the bar is red and stretches the full y-axis length of the chart (On click, opens the “Add historical data” modal with the date pre-selected to the date of the bar. On hover, color gets darker to show that the bar is a click target. Clicking on the hover text should also open the modal)
6. When there is data for a day, the bar is green and has a height of the # of confirmed cases (On click, opens the “Add historical data” modal with the date pre-selected to the date of the bar, on hover, shows the date, case count, and a CTA to click to change the case count. Click on the hover text should also open the modal)
7. P2: If a case count is 0 or less than 50% between the first y-axis line and 0, display the count above the bar
8. Button at the top right “+ Add Historical Data” to open the “add historical data” modal with yesterday’s date pre-selected (or the default we are currently using)
9. Because the “add historical data” modal allows users to be able save case and population data together, we do not anticipate the scenario in which they have case data entered but no population data or vice versa.

Mocks: https://www.figma.com/file/6z1QQW84a59Ul3c17PgWdV/%F0%9F%9A%80Recidiviz-CJStatus-(excalibur)?node-id=2206%3A7614

**Describe alternatives you've considered**
We considered showing a table or calendar widget that indicates historical data and data missing. A bar chart lets them see the trend over time. A line chart was also considered, but it is more challenging to interact with.

**Additional context**
This information is repeated in this doc, in case there are complications that warrant a longer discussion: https://docs.google.com/document/d/1KRCYPeC3W7KJm7flUpZKPxdhL7U0sRTfisD0cjqQYuM/edit#heading=h.qo0qd95ajfm1

This is deeply related to #404

**Comment by jessex** [comment]
@sychang, clarifying: those text labels of "Cases" and "Resident Population" above the bar chart basically function as checkboxes? It defaults to _both_ enabled, which overlays cases atop resident population, but you can turn one of them off and see only that set of bars, right? Is it possible to turn both off?

Another clarifying question, regarding number 9: even though the modal allows you to enter data about both, it's not actually a point of validation, so it's totally possible (and I'd argue probable) that there could be a date which will have only one or the other of cases or resident population data. In fact, I'd wager that nearly all developers working on the project have facilities which are partial in this way. Given that, I think we need to have some design for the scenario instead of assuming it won't happen. What do you think?

**Comment by sychang** [comment]
Correct, they function as checkboxes. Default is on, and it is possible to turn both of them off. In that case, it would function similar to the output projection chart on the facility detail page, wherein the chart is blank when a user deselects all 4 curves.

![image](https://user-images.githubusercontent.com/6633887/81854793-0f85a700-9524-11ea-895b-3ec0b9611f8b.png)

Agree on your second clarifying question - the validation concern is related to the broader issue @macfarlandian and I were talking through about letting users easily add correct data for each day. I'm thinking through that piece a bit more. If we put validation aside, the existing modal by default pre-populates information about both cases and population, so IIUC when a user clicks save, both cases and population are saved at the same time even if a user only updated one field. That said, I am considering this scenario when thinking through the overall data entry flow.

**Comment by daschi** [comment]
I think this issue might be dependent/blocked by getting #404 done first, since it will be the same chart. I'm still thinking through setting up the bar chart with this data, so if someone else wants to also work on this and pair let me know.
