### ISSUE TITLE
[Excalibur fast follow] Generate impact report on non-baseline scenarios

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#406]
**Is your feature request related to a problem? Please describe.**
Users often build hypothetical scenarios to test what would happen if they planned releases or took certain steps to mitigate the spread of covid-19. We want to help them model what the impact of their actions would be so they can pick the most positive course of action or justify their actions to key stakeholders.

This will also enable our state engagement team to help states states model hypothetical actions.

**Describe the solution you'd like**
Currently, we are only able to generate an impact report on the baseline scenario. Now that multi-scenario support is launched, we want to be able to generate this impact report for any non-baseline scenarios.

1. Add "Generate Impact Report" on non-baseline scenarios
2. There may be some slight copy changes needed for this, Serena to add here if that's the case.

**Additional context**
N/A

**Comment by daschi** [comment]
@sychang would these other scenarios' impact reports use the same user-added population inputs (from the modal) as the baseline scenario? If they change the inputs for that modal, should those populations be tied to that particular scenario, or shared across all scenarios?

**Comment by sychang** [comment]
They can share those population inputs across all scenarios!
