### ISSUE TITLE
Refactor facilities detail page/new facilities page URLs

### ISSUE THREAD

**Issue by rememberlenny** [Recidiviz/covid19-dashboard#411]
**Is your feature request related to a problem? Please describe.**
Currently the facility detail page can only be accessed through the facility dashboard. Also refreshing the page on the facility detail page unintuitively navigates to the "new facility" page. 

**Describe the solution you'd like**
Refactor the facility detail page so that the facility ID is in the URL (`$root_url/facility/$facility_id`). Also make the new facility page its own URL (`$root_url/facility/new`).

This also means that navigating directly to the `/$facility_id` url will properly load the facility data into the page.

**Additional context**
This will also be important for making sharable facility details pages.

**Comment by jessex** [comment]
This seems like the right approach to me, @rememberlenny. 

@sychang, when we complete #406, presumably we will have a similar issue where refreshing the `/impact` page will have undefined behavior, because how would you know which scenario you are trying to refresh Excalibur for? We may want to pursue that same plan above for `/impact` while we are at it in this issue. Thoughts?

**Comment by sychang** [comment]
Great catch, that makes sense to me!

**Comment by sprad** [comment]
@rememberlenny - we will likely want to include the Scenario ID in the URL as well, like so:

```
$root_url/scenario/$scenario_id/facility/$facility_id
```

This will be important for a few reasons:

1.  While I think it's technically possible to query sub-collections directly via something called a "[collection group query](https://firebase.google.com/docs/firestore/query-data/queries#collection-group-query)" this requires some additional infrastructure to be in place.  From the docs:

> Before using a collection group query, you must create an index that supports your collection group query. [You can create an index through an error message, the console, or the Firebase CLI](https://firebase.google.com/docs/firestore/query-data/indexing).
>
> For the web and mobile SDKs, you must also [create rules that allow your collection group queries](https://firebase.google.com/docs/firestore/security/rules-query#secure_and_query_documents_based_on_collection_groups).

2.  It may be challenging to easily know which Scenario we'd like to add a new facility to using this URL:  `$root_url/facility/new`

3.  While it's unlikely to be a problem, I don't think there is any guarantee that an ID generated within the facilities sub-collection is unique across all other sub-collections.  In other words, it may be possible that the proposed URL (`$root_url/facility/$facility_id`) returns more than one facility.

**Comment by rememberlenny** [comment]
This is great @sprad . Will be able to implement this quite easily.

**Comment by macfarlandian** [comment]
closing, see linked PR for context
