### ISSUE TITLE
Update Recidiviz auth0 sign-ups to collect names

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#419]
**Is your feature request related to a problem? Please describe.**
At the moment we don't collect user's names (e.g., Carl E. Washbuckle) during the sign-up flow for our products, and as a result we can't support U2U actions like sharing very easily (because we can only refer to other people by their e-mail addresses).

**Describe the solution you'd like**
We should update our sign-up forms (for Covid, and preferably for Lantern and ND/ID as well) to collect a name for users (required field) with the following validation criteria:
- It can be any string of letters, spaces, or symbols in the set [.,-()]
- It must include at least 1 letter

**Describe alternatives you've considered**
- We can (and likely someday will) allow users to update their names in Settings, as well, but that doesn't guarantee a name to use in sharing dialogues, etc.

**Additional context**
When discussed w/Josh, he found some Auth0 documentation that would be relevant:
https://auth0.com/docs/libraries/lock/v11/configuration#additionalsignupfields-array-

**Comment by jessex** [comment]
Authentication x UX x Feature is now known as _the Easter Special_. Look at those colors.

**Comment by sprad** [comment]
One additional piece of work would be to update this information for existing users.  I'm assuming this could be done relatively quickly manually if someone is generally capable of recognizing the existing email addresses within our system and mapping them to a name.

**Comment by cawarren** [comment]
@sprad Definitely, I ran a list of users yesterday and know names for almost all of them.

**Comment by macfarlandian** [comment]
This code lives in the Auth0 console so there is no pull request required here. So by way of accountability you are all hereby informed that this is done! I have verified that names entered in this new signup field wind up properly stored in our Firestore `users` collection.

Here's what the new form looks like: 

![Screen Shot 2020-05-20 at 3 54 14 PM](https://user-images.githubusercontent.com/5385319/82507743-f21e8300-9ab7-11ea-9f10-b2529c438278.png)

![Screen Shot 2020-05-20 at 3 53 51 PM](https://user-images.githubusercontent.com/5385319/82507750-f77bcd80-9ab7-11ea-8bea-ad0ab336f8f7.png)

Closing this issue, but if you hate this for some reason feel free to reopen and/or yell at me

**Comment by jessex** [comment]
Very nicely done, @macfarlandian! No issues from my end.

**Comment by sprad** [comment]
I dig it! :shipit:
