### ISSUE TITLE
Changing scenarios creates issues in facility state management

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#444]
**Describe the bug**
There is a suspected bug in state being appended when switching between scenarios (rather than resetting it). The bug impacts a couple of issues:

#406 When you generate an impact report on a non-baseline scenario, the R(t) calculation includes facilities from both the baseline as well as non-baseline scenarios (e.g., I had 6 in baseline and 7 in hypothetical scenario and the impact report for my hypothetical scenario showed 13 facilities)

#415 summary stats are not accurate when another scenario has been loaded.

**To Reproduce**
Steps to reproduce the behavior (write-up courtesy of @jessex)
1. Log into app and generate an impact report for your baseline scenario (the R(t) chart will sum up to the right number of facilities).
2. Go back to scenario details, then select a different scenario. 
3. Then switch back to baseline and generate an impact report again. Now the denominator in that chart will include the number of facilities from the other scenario. It seems like as we switch between scenarios, we are appending to some collection of state and not resetting it. 

**Expected behavior**
The denominator for the impact should always only include the facilities that are in a given scenario.

**Desktop (please complete the following information):**

- OS [e.g. Windows 10]: Mac OS Catalina 10.15.3
- Browser [e.g. chrome, edge]: Chrome
- Version [e.g. 22]: 81.0.4044.138

**Additional context**
N/A

**Comment by jessex** [comment]
@daschi did an [initial investigation](https://github.com/Recidiviz/covid19-dashboard/pull/427#issuecomment-629832387) and found what appears to be the root cause. Copying her comment in full for posterity:

>@jovergaag You may have already found this, but since I had also worked on the rt summary stats I was curious and looked into it. The bug is coming from the `rtData` value returned from the `FacilityContext` on line 60 in the `ResponseImpactDashboard`, it looks like it is collecting the rtData for all facilities across all scenarios that it has been requested for.
