### ISSUE TITLE
Change of case or population count in AddCaseModal does not persist on second open

### ISSUE THREAD

**Issue by jovergaag** [Recidiviz/covid19-dashboard#462]
**Describe the bug**
When using the Add Cases Modal to update case or population count for a facility, the updated case/population number is saved on the facility but if the modal is opened again for the same facility, it shows the old case/population numbers.

**To Reproduce**

1. Go to the multi-facility (home) page
2. Make a note of the cases and residents numbers in the first FacilityRow
3. Click on the cases link to add a new case count for the first FacilityRow
4. Change the case count and hit 'Save'
5. Notice that the case count is reflected correctly in the Facility Row and the System Summary counts update correctly.
6. Click on the cases link one more time for the first Facility Row
7. Note that the number shown in the current case input field is the old case count, not the number you just saved. 

**Expected behavior**
The updated case or population counts should persist each time the modal is opened. 

**Screenshots**

**Desktop (please complete the following information):**
 Os X
Chrome
Most likely across all platforms

**Smartphone (please complete the following information):**

**Additional context**
The same problem exists for case and population counts.

**Comment by jessex** [comment]
@sychang, I leave it to you to prioritize this one. Feels like medium-ish priority to me, since it's more of a UX concern than an actual functionality issue.

**Comment by sychang** [comment]
Thanks for flagging! I will keep it medium-low for now because we have a few UX improvements incoming that will help better indicate whether a given input is user entered or pulled from default or public logic, and this issue could be wrapped within that.

**Comment by daschi** [comment]
@jovergaag I'm not able to reproduce this bug on master following the steps above, I think maybe it has been fixed along the way. Just wondering if you have a chance can you check to see if you can still reproduce it?

**Comment by jovergaag** [comment]
@daschi I just tried to reproduce this on master and you're correct, this is no longer an issue.  Closing!
