### ISSUE TITLE
Fix "Save" button to the bottom of facility detail page to be always visible when editing a facility

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#467]
**Is your feature request related to a problem? Please describe.**
After observing states use the dashboard, a regular behavior we are seeing when states go to add a facility is that they input some information in the facility detail page but do not scroll all the way to the bottom and do not see the "save" button. They instead click the "Recidiviz" logo, which takes them back to the homepage without actually saving the facility. We would like to make it 

**Describe the solution you'd like**
Upon entering the facility detail page, the save button is always fixed to the bottom of the page so it never goes out of view. To avoid visual overlap, the save bar can be, vertically centered in a horizontal bar 100px in height the same color as the facility detail page background.

![image](https://user-images.githubusercontent.com/6633887/82522674-c0c1a980-9aef-11ea-984f-38def8653739.png)

**Describe alternatives you've considered**
Adding an additional save button at the top of the facility detail page so it's guaranteed above the fold. If this alt is significantly easier, we can create a mock that could work.

**Additional context**
N/A

**Comment by rocktacular** [comment]
@sychang please see gif in PR above and lmk if that looks ok

**Comment by sychang** [comment]
Looks good, thanks!
