### ISSUE TITLE
Run script over Firebase to use `facilityOccupancyPct` values to populate `facilityCapacity` 

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#490]
**Is your feature request related to a problem? Please describe.**
Issue #203 updates the model behavior to take in the actual facility capacity, rather than the current % of that capacity, so that the model does the work to figure out % capacity rather than making the user do it.

As a result, we're going to need to run a script over the current Firestore (or in FE JS when one value is found to exist and the other doesn't, or something else) to populate the new facility capacity field (`facilityCapacity`) using the old data (`facilityOccupancyPct`).

**Describe the solution you'd like**
We should populate `facilityCapacity` for facilities where a) there is no current `facilityCapacity` value, and b) there is a current `facilityOccupancyPct` value.

The new `facilityCapacity` value should be the old `facilityOccupancyPct` value multiplied by the sum of the resident population in the facility for the last data point where both (population and `facilityOccupancyPct`) are present.

**Describe alternatives you've considered**
- We could leave the value blank, effectively wiping this value for all users who've previously entered a `facilityOccupancyPct` value

**Additional context**
- See Issue #203

**Comment by macfarlandian** [comment]
this migration script was run succesfully in concert with #507
