### ISSUE TITLE
Show summary projection chart under summary stats on homepage

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#514]
**Is your feature request related to a problem? Please describe.**
One benefit of today’s existing daily report is the ability to show the projection for the entire scenario. On the web tool, there is currently no easy way to see this system aggregate. The “system summary” stats (#415) was a first step at beginning to abstract some of the system-level information out to the landing page. We would like to take an extra step and add the aggregate system-level projection to the homepage.

**Describe the solution you'd like**
In scope:
- Show the chart for the aggregate exposed, infectious, hospitalized, fatalities projection for the overall system (this was done already in Excalibur). Allow each line to be toggled on and off similar to the treatment in the facility detail page. **By default, have these lines off.**
- Include an additional line for the **cases** projection for all facilities in a system. **This should be the only line on by default.**
- Cases = sum of everything except susceptible on the calculations (cases = exposed+infectious+hospitalized+recovering+recovered+deaths). Note, this is the same information that can be found in the projection table under “cases.”
- On hover for each day, break down cases by inmates and staff. Copy in the image below.
- P2: Show confidence intervals, the edges of which represent an optimistic and pessimistic scenario (should be able to leverage #76)
- P2: Allow the ability to toggle on and off

Out of scope, but would consider for later versions

- Add ability to toggle on and off generic rates of spread and change different variables (e.g., click on a system summary card to change it hypothetically)
- Show the same curves that are on the facility detail view
- Show aggregate historic case counts for the entire system for the past 4 days

TODO: Real mocks incoming, but it will likely live on the home page and be slotted in the System Summary, with a similar visual style as the other charts in the app. 
Please excuse the truly horrendous concept mock in the meantime:
![image](https://user-images.githubusercontent.com/6633887/83431590-2b7eb900-a3fd-11ea-8c92-9d8c115e645d.png)

**Describe alternatives you've considered**
- Showing a chart with only cases on the homepage. This might be confusing because it may be less clear how it connects to the individual facility projections.

**Additional context**
A similar aggregate projection curve was already created for excalibur, so there may be a way to leverage existing work there.

**Comment by jessex** [comment]
>One benefit of today’s existing daily report is the ability to show the projection for the entire facility.

Do you mean for the entire scenario?

**Comment by sychang** [comment]
Yeah entire scenario, my bad - updated the original comment.

**Comment by macfarlandian** [comment]
closing, see linked PR for context
