### ISSUE TITLE
[Shadow baseline] Create shadow baseline scenario that can "sync" to a user's baseline scenario

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#521]
**Is your feature request related to a problem? Please describe.**
[PRD for more context](https://docs.google.com/document/d/1e6yCfUUYIZW0FlTkzzwYg80-wymZ7PkTClo_k7bqUqk/edit?ts=5ed53a10#). We currently ask users to enter complete data about every facility in their system, daily, in order to get a picture of what’s happening in their system. This is an effort to reduce the data input work on their end in order to improve retention and reduce user friction. 

We already pull in county case and death data for every county in the United States, which reduces the end-user’s workload. To further reduce the end-user workload, we will pull in:
- Facility metadata (name, address, county, capacity, population, security level, year built)
- Case, test, and death count per-facility

This data has been collected by our partners and manual collection team over the course of the past month. It is patchy in some places, meaning we need to not promote this sync when the information is mostly unavailable. Data sources to power SBS can be found in the PRD.

**Describe the solution you'd like**
**Creating a Shadow Baseline Scenario**
We will create a Shadow Baseline Scenario (SBS) for each state, which auto-fills based on our data collection efforts. Users will not be able to see or affect the SBS - we will maintain it with external data regardless of any end-user activity.

If the user opts to turn on ‘Sync’ for their Baseline Scenario (BS), we’ll check once a day for updates to the SBS, and if found, propagate them to the user’s Baseline Scenario. Sync is unidirectional - it only applies from the SBS to the BS. 

**Sync behavior**
If the user overwrites a value in their BS that was propagated from the SBS, that value should not be overwritten again by the SBS. 

Examples:
If the user updates facility metadata (e.g. capacity, or the facility name), it will not be overwritten by the SBS moving forward. 
- In spite of this, the syncer should still be able to recognize the facility even if the name is different. TODO: Address UX of this.

If the user updates the case counts for facility ABC on day 6/1/2020 to ‘242’ (where the SBS had inserted ‘241’), that day will not be overwritten again by SBS. The syncer will update values for future days, however.
- In spite of this, for case- and death- data, the syncer should pull the prior day’s value if it’s larger than the value available in SBS (since larger numbers are presumably more recent / accurate)

Note that this means there is a 1:M relationship between the SBS and BSes, since multiple users may exist / have BSes in the same state.

**Describe alternatives you've considered**
We have considered a bi-directional SBS <> BS mapping where the user can opt in to have their data "contribute" to the public data collection effort. However that is too complex for now and there are non-technical solutions for gathering data from states into SBS.

**Additional context**
P2: In the short-term (pending design), SBS could also power the data behind the weekly email reports (PRD), which are currently constructed manually.

**Child Issues**

- ~Always fetch model versions along with facility #595~
- ~Fetch shadow data for baseline scenarios #565~
- ~Create composite Facility objects with reference data #605~
- ~When creating a new facility, pick a shadow baseline facility to sync it to #559~
- ~Ingest Covid Case Data on a Daily Basis #566~ 
- ~Update the Data Model to Support Determining Whether or not a Reference Facility is "New" #604~
- ~When a new data shadow facility is found, enable mapping to existing facility #560~
- ~Import facilities for new users or those without existing facilities #557~
- ~Adding a Sync Reference Facilities Toggle #632~
- ~Only Allow Syncing of Reference Data on the Baseline Scenario #635~

**Remaining Work and Launch Blockers**

- Import Facility Reference Metadata into Firestore #640 
- Visually Distinguishing Public Data Inputs from User-entered Data #558 (WIP in [this branch](https://github.com/Recidiviz/covid19-dashboard/tree/philihp-input-shadow))
- Let Users Match Existing Facilities to Shadow Facilities #556 
- Cases Data and Chart/Visualizations Not Updating #641 
- Toggle the App to Use the Production Covid Case Data #642 (**_All other issues must be completed first!_**)

**Comment by jessex** [comment]
@sprad, @macfarlandian: this is the next big feature we'll want to start tackling today. More frontend-focused issues will be filed by @sychang in the days to come, but this is the substance of the backend for the feature and should be unblocked to start on designing and building.
