### ISSUE TITLE
Save to Facility, after Duplicate, raises errors.

### ISSUE THREAD

**Issue by glen0071** [Recidiviz/covid19-dashboard#544]
**Describe the bug**
When you hit save on a duplicated facility, it raises errors.

I see `Cannot set property 'id' of undefined`
<img width="934" alt="Screen Shot 2020-06-08 at 10 52 23 PM" src="https://user-images.githubusercontent.com/8259050/84104266-cd446e00-a9da-11ea-82d7-4b0e5884aaea.png">

[Google doc](https://docs.google.com/document/d/1OUzZnV4S9JGqUULkbTOEKUs4HTzqB73gsPuvqS2buC0/edit) also showed permission errors but not seeing those anymore.

**To Reproduce**
If you’re in a shared scenario you don’t own, and on the Facility Details page of that scenario for a facility, and and click ‘Duplicate’ in the upper-right, everything seems to work as expected. But if you try to hit ‘Save’ on the facility (once it’s copied), you get an error,

**Expected behavior**
Send the user back to the Scenario Details page for the newly duplicated scenario.

**Desktop (please complete the following information):**
- OS [e.g. Windows 10]: OS X
- Browser [e.g. chrome, edge]: Chrome

**Comment by glen0071** [comment]
@jessex working on an error from that polish round Google doc.

After reproduce steps (1. view a Shared Scenario, 2. view details on a Facility within that Shared Scenario, 3. click duplicate, 4. click save) I am not sure of the expected behavior.

If I am viewing Facility Details for Facility Foo within a Shared Scenario and I hit "Duplicate", I am...
Option 1: Duplicating that one facility onto one of my Scenarios.
Option 2: Duplicating the whole scenario (which automatically saves the Scenario as my own under the default "Copy of... [name]"),  and then the Facility Foo details I'm looking at are within my "Copy of... [name]" Scenario, and I should be able to save changes made to Facility Foo within that screen.

I suspect Option 2 was intended, and some data from the Shared Scenario's Facility is not getting flushed out when the newly minted Facility should be visibly in the browser.

**Comment by jessex** [comment]
Can you send a screenshot of which button you are pressing when you say 'If I am viewing Facility Details for Facility Foo within a Shared Scenario and I hit "Duplicate"'? Which "Duplicate" are you referring to exactly? We can duplicate scenarios and also duplicate individual facilities, so we want to be sure we're talking about the same thing.

**Comment by glen0071** [comment]
Here's the button
<img width="885" alt="Screen Shot 2020-06-08 at 11 23 51 PM" src="https://user-images.githubusercontent.com/8259050/84105871-362de500-a9df-11ea-8621-d3db62b6c67e.png">

Also, when I place debuggers in the code, `src/page-multi-facility/ReadOnlyScenarioBanner.tsx` has a `duplicate` function that calls on `duplicateScenario` which appears to do all the duplicating, and then calls `dispatchScenarioUpdate`.

**Comment by glen0071** [comment]
@jessex you see my response to your last question?

**Comment by jessex** [comment]
Thanks, @glen0071! With those instructions I was able to replicate this. Furthermore, when I then went back to the Scenario Details page, I found I was correctly in my duplicated version of the scenario and upon clicking back into the same Facility Details page I was on previously, I now could make edits and click save.

Given that, I suspect what is happening is that when you're on the Facility Details page and you click _Duplicate_, it's not properly "resetting"/updating the scenario state in the app to move you over to the facility in the new/duplicated scenario, but keeping you "inside of" the original/shared scenario, thus causing edits to fail.

I don't know what the expected UX for this feature was, though. It might be that when you click "Duplicate" on that bar, you are supposed to be sent back to the Scenario Details page for your newly duplicated scenario, regardless of which page you are on when you click that button. If so, that gets around this issue nicely. But if we want you to be able to click that button and stay on Facility Details and immediately start making edits, the fix will be a bit more involved.

CC @sychang to weigh in!

**Comment by sychang** [comment]
Just replicated it - thanks for the detailed instructions! I'm also not sure the originally intended UX, but I would be in favor of sending the user back to the Scenario Details page for the newly duplicated scenario, regardless of page when you click the duplicate button. Based on what Josh is saying, this seems to be the more straightforward engineering solution and also feels like the nicer UX solution so the user knows exactly what action has occurred (vs. when I was reproducing the bug and clicking "duplicate" merely made the banner disappear, I was confused whether I could/should be editing the scenario and if it was now my own).

**Comment by glen0071** [comment]
That all sounds great. Thanks for the input, I'll make it so.
