### ISSUE TITLE
[Shadow sync config] Let users match existing facilities to shadow facilities

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#556]
**Is your feature request related to a problem? Please describe.**
This is a user-facing component of the shadow baseline project to pre-populate user scenarios with publicly collected data to reduce their data entry workload so we can improve retention and reduce user friction.

Once we launch the feature, for users that already have facilities in their model, we need them to do a one-time mapping of their facilities to our shadow data so we can sync the data moving forward.

**Describe the solution you'd like**
Users who already have facilities in the model will create a 1-1 mapping of our shadow baseline scenario (SBS) facilities to their user-entered baseline scenario (BS) facilities. 

In steady state, users can access this modal from a button in the left column according to the [trigger logic](https://docs.google.com/document/d/1e6yCfUUYIZW0FlTkzzwYg80-wymZ7PkTClo_k7bqUqk/edit?ts=5ed53a10#heading=h.efwt1m8okoy2) in the PRD:

![image](https://user-images.githubusercontent.com/6633887/85311745-81ce9d00-b47b-11ea-8f0c-c561fc213d1f.png)

For the modal:
- Key the sync config content based on the "State" and "Type of System" information from the first facility in the user's model (there will be a separate issue to only trigger this feature when state and type of system match across all facilities).
- For SBS facility, users have the option to select an existing BS facility, to "Add as a new facility" (if the facility is not currently modeled), or "Don't sync this facility" if they do not want the SBS facility added to their model.
- A green sync icon will appear next to existing facilities and the “Add as new facility” option, the green sync icon will appear in the input box
- This process should not change the name of their facility
- Save should be disabled until the user makes at least one selection in the dropdown
- A toggle should allow them to turn off the preopulated data entirely. If they were to turn it off and on again, we should remember which facilities they already had synced.

![image](https://user-images.githubusercontent.com/6633887/85311810-9874f400-b47b-11ea-903e-3ab03a558844.png)

![image](https://user-images.githubusercontent.com/6633887/85311969-d114cd80-b47b-11ea-9e3d-83ccaf2bc5cf.png)

When we first launch the feature, this modal will be a promo with a few minor tweaks:
1. Remove the toggle
2. Replace "Cancel" with "Not Now"

![image](https://user-images.githubusercontent.com/6633887/85311855-aaef2d80-b47b-11ea-9a98-beea42ac3354.png)

**Describe alternatives you've considered**
N/A

**Additional context**
Full details in [PRD](https://docs.google.com/document/d/1e6yCfUUYIZW0FlTkzzwYg80-wymZ7PkTClo_k7bqUqk/edit?ts=5ed53a10#)
[Engineering design doc](https://docs.google.com/document/d/1mvuQpXMPf3V164D4B7waCRArONw9iOWvE1g2SsLh03A/edit#heading=h.3ez6its1yt01) covers some relevant architectural concerns

Mocks: https://www.figma.com/file/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=2758%3A0

Backend ticket: #521 
Other UX tickets: #557 #558 #559 #560

**Comment by macfarlandian** [comment]
@sychang should you be able to save without actually mapping any facilities? or do we want to disable saving or raise an error message or something when that happens?

**Comment by sychang** [comment]
Great question, @macfarlandian - let's disable saving until they at least map one facility.

There is a second question of do we want to disable saving until they have made a selection for _all_ of their facilities? I think the answer is no, we should enable the save button after a dropdown option has been selected for _any_ facility to increase the chance of a user using the feature because they may want to see what it does on one facility before coming back and turning it on for others.

**Comment by sychang** [comment]
@sokunthel @macfarlandian @daschi FYI updated the copy for this in the original comment
