### ISSUE TITLE
[Shadow baseline] Visually distinguishing public data inputs from user-entered data

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#558]
**Is your feature request related to a problem? Please describe.**
This is a user-facing component of the shadow baseline project to pre-populate user scenarios with publicly collected data to reduce their data entry workload so we can improve retention and reduce user friction.

When a user has their baseline scenario synced with a shadow baseline scenario, we need to make it visually clear which inputs are pulled from public data vs. which inputs they have entered themselves or overriden.

**Describe the solution you'd like**
For all individual inputs (whether in the facility details page or add data modal), inputs with a green sync icon signal that particular input is from the shadow public data, whereas an input without the sync icon indicates user data (or no data). When a user overrides a shadow data input, the green sync icon should disappear.

![image](https://user-images.githubusercontent.com/6633887/84345598-63ab9780-ab73-11ea-8671-2504b7c4dfe4.png)

In the scenario library view, if a facility is synced to shadow data, add the sync icon next to the "last updated" date. The last updated date should reflect the date at which the syncer last ran or when the user last modified their data:

![image](https://user-images.githubusercontent.com/6633887/84456642-1e946d80-ac26-11ea-9de1-8eeacc82bd1c.png)

**Describe alternatives you've considered**
N/A

**Additional context**
Full details in [PRD](https://docs.google.com/document/d/1e6yCfUUYIZW0FlTkzzwYg80-wymZ7PkTClo_k7bqUqk/edit?ts=5ed53a10#)

Data model [design document](https://docs.google.com/document/d/1mvuQpXMPf3V164D4B7waCRArONw9iOWvE1g2SsLh03A/edit?usp=sharing)

Mocks: https://www.figma.com/file/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=2758%3A0
TODO: Finalize copy

Backend issue: #521
Related front-end issues: #556, #557, trigger logic issue incoming
TODO: We'll add the green sync icon in a couple more places (next to facility in scenario library view, etc.), mocks and issue incoming

**Comment by philihp** [comment]
Hi! I need to take a step back from the project for a sec so I'm removing myself from this ticket. What I had done so far was pushed to the branch https://github.com/Recidiviz/covid19-dashboard/tree/philihp-input-shadow, hopefully it gives the next person a start
