### ISSUE TITLE
[Shadow, sync config] When creating a new facility, pick a shadow baseline facility to sync it to

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#559]
**Is your feature request related to a problem? Please describe.**
This is a user-facing component of the shadow baseline project to pre-populate user scenarios with publicly collected data to reduce their data entry workload so we can improve retention and reduce user friction.

During steady state, users who have their baseline scenario (BS) synced with the public shadow baseline scenario (SBS) may choose to model a new facility. We want to make sure new facilities created after sync is turned on can be synced to the latest public data.

**Describe the solution you'd like**
If sync to public data is turned on, when adding a new facility, on-save, we prompt the user to assign an SBS facility (opens the Sync Config dialog):
![image](https://user-images.githubusercontent.com/6633887/84346474-a8d0c900-ab75-11ea-9f0b-39c381457282.png)

All facilities begin "unselected" or grayed out. Only one facility may be selected at once.

![image](https://user-images.githubusercontent.com/6633887/84346496-b71ee500-ab75-11ea-8642-f92d52c5dcd9.png)

**Describe alternatives you've considered**
N/A

**Additional context**
Full details in [PRD](https://docs.google.com/document/d/1e6yCfUUYIZW0FlTkzzwYg80-wymZ7PkTClo_k7bqUqk/edit?ts=5ed53a10#)

Data model [design document](https://docs.google.com/document/d/1mvuQpXMPf3V164D4B7waCRArONw9iOWvE1g2SsLh03A/edit?usp=sharing)

Mocks: https://www.figma.com/file/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=2758%3A0
TODO: Finalize copy

Backend issue: #521
Related front-end issues: #556, #557, #558, trigger logic issue incoming

**Comment by sychang** [comment]
@daschi another one here with updated copy for the modal:

![image](https://user-images.githubusercontent.com/6633887/85311258-c73e9a80-b47a-11ea-90b6-e3c72248f0f7.png)

**Comment by daschi** [comment]
@sychang This one is already merged to master, but I can include the copy update in my PR for #560 if that's okay.

**Comment by sychang** [comment]
Yeah that's perfect, no rush
