### ISSUE TITLE
Separate recovered/deceased cases from case count for projection

### ISSUE THREAD

**Issue by sychang** [Recidiviz/covid19-dashboard#561]
**Is your feature request related to a problem? Please describe.**
As states are reaching steady state in fighting COVID, lots of incarcerated individuals have recovered and a state's cumulative case count is no longer the best indicator of their projection (because the model currently assume mid-outbreak on the cumulative cases). 

**Describe the solution you'd like**
Allow states to tell us how many of their covid cases are "recovered" or "deaths" so we can separate those from the projections.

1. (UI) In the add cases modal, add a column of inputs between "CURRENT CASES (CUMULATIVE)" and population labeled "RECOVERED CASES"
2. (UI) Add a second column to the right of recovered labeled "DEATHS"
3. (UI) Change the label of "CURRENT CASES (CUMULATIVE)" to "CUMULATIVE CASES"
4. (UI) Repeat 1-3 in the facility detail view
5. (UI) Update the copy in the add cases modal to say "Enter the number of cases detected and the total population as of this date."
6. (Model calculation) In creating the projection curve, we will now be projecting based on "active" cases only, which is cumulative - recovered - deaths.

**Describe alternatives you've considered**
- We could have states directly enter "active" cases but it is less common for states to have that data readily available.
- We could have the model take "new" cases instead of cumulative cases, but may not be a number states readily have available.
- We could not make the change and leave it as cumulative cases, but we risk some states abandoning the model because it does not accurately represent their system at present anymore.

The proposed approach also aligns with our shadow data collection efforts, which are tracking the number of recovered cases.

**Additional context**
There will be a few model updates as a part of this change:
1. Updating the projection to distribute cases across the active and recovered buckets 
2. Update the r(t) calculation so it becomes a smoothed 7-day rolling average
3. Remove the r(t) hack for discarding duplicate counts

**Comment by sychang** [comment]
Confirmed model methodology with @justkunz and @cawarren , so the frontend update to the add cases modal (steps 1-5 above) is ready to be worked on in parallel!

**Comment by justkunz** [comment]
One question about the cumulative cases vs recovered cases is how facilities should count deaths. I think a tooltip to guide them to add deaths in "recovered" or adding a separate input for deaths would be the best options. I prefer the separate input, but can make it work if deaths are included in "recovered" instead.
