### ISSUE TITLE
Add dynamic R(t) calculaton to model

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/covid19-dashboard#62]
As users update case counts over time, we can derive an observed rate of spread and use that to make adjustments to the initial constants per facility.

**Comment by cawarren** [comment]
*Update:*
- @justkunz has implemented this in Python, and is working on some small revisions on the modeling side as well as some updated epidemiology variables.
- Juan and I are working on a UI treatment, but it shouldn't block implementation of dynamic R(t) calculation as part of the model.

**Comment by cawarren** [comment]
As a note on why this will be prioritized fairly high this week: Many more facilities are now seeing cases, and the rate of spread varies significantly between them. 

A one-size-fits-all model worked well for directional use when forecasting different scenarios, but now that states are in the thick of things they need to be able to see a customized version of where they're at in facilities and whether they're on the right track.

If it's helpful to understand contextually what R(t) ends up looking like, check out rt.live as an example (that website is tracking it for the general population in different states, but using the same methodology we're implementing).
