### ISSUE TITLE
/impact data not displaying correctly

### ISSUE THREAD

**Issue by amyrlam** [Recidiviz/covid19-dashboard#638]
**Describe the bug**
/impact data not displaying correctly

**To Reproduce**

1. Go to /impact
2. See NaN and no graphs

![image](https://user-images.githubusercontent.com/1372946/86879990-e3f4e800-c0a0-11ea-8c04-8c1e7c7f97e0.png)

My facilities for reference: 
![image](https://user-images.githubusercontent.com/1372946/86879957-da6b8000-c0a0-11ea-8917-76a7c1d7e43c.png)

**Expected behavior**
This error goes away if we revert the last commit e.g. `git co fb49a28c37bc0d82114f424d46acb1997c9295f7`

1. Go to /impact
2. See no NaN and yes graphs

Same facilities /impact appear as it should be: 
![image](https://user-images.githubusercontent.com/1372946/86880103-16064a00-c0a1-11ea-8088-2a61c95b6015.png)

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.

This is fake data

**Desktop (please complete the following information):**

- OS [e.g. Windows 10]: Mac OS 10.15.5
- Browser [e.g. chrome, edge]: Chrome
- Version [e.g. 22]: Version 83.0.4103.116 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

N/A

**Additional context**

Kinda similar to: https://github.com/Recidiviz/covid19-dashboard/issues/591

**Comment by jessex** [comment]
@amyrlam this is only locally, right? I tried to reproduce it locally but could not.

**Comment by amyrlam** [comment]
@jessex It's possible my local data is borked! Will ask @ standup if anyone can repro on master / localhost

**Comment by amyrlam** [comment]
@jessex paired with @macfarlandian, who can not repro locally. @neeharmb could not repro either. maybe my local is just stale since i haven't been as active on the project lately or some other local oddity? so seems safe to close for now and move forward, revisit if comes up

**Comment by amyrlam** [comment]
ref: https://recidiviz.slack.com/archives/G010VACT8F2/p1594186263003300
