### ISSUE TITLE
[Shadow Data] Toggle the App to Use the Production Covid Case Data

### ISSUE THREAD

**Issue by sprad** [Recidiviz/covid19-dashboard#642]
**Is your feature request related to a problem? Please describe.**

At the moment, we’ve siloed our app to read Shadow Reference Data from a Firestore collection called `reference_facilities_test`.  We also store the mapping of user facilities to reference facilities in an attribute on the user's Baseline scenario called `testReferenceFacilities`.  Both of these "pointers" will need to be updated to `reference_facilities` and `referenceFacilities` respectively when we launch.  The specific changes will need to be made [here](https://github.com/Recidiviz/covid19-dashboard/blob/3dc6fc9ede152798ee96f5de5b2bb5d3d18192e0/src/database/index.tsx#L57) and [here](https://github.com/Recidiviz/covid19-dashboard/blob/3dc6fc9ede152798ee96f5de5b2bb5d3d18192e0/src/database/index.tsx#L60).

**WARNING:**  This should not be done until all other Shadow Reference Data Issues have been completed and QA'ed as noted in this parent issue: #521

**Comment by macfarlandian** [comment]
closed by #698
