### ISSUE TITLE
Improve performance for large scenarios

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/covid19-dashboard#657]
**What needs to be done? Why does it need to be done?**
As shadow data features have started to come online, making it easier to bulk-add a large number of facilities to a scenario, we are seeing performance start to suffer on the multi-facility dashboard. The task here is to investigate this and either solve it or file tickets for the proposed solution if it is more involved. 

"Large" here means somewhere in the neighborhood of 10+ (can vary since it is likely an issue of memory consumption).

**Additional context**
We do know some potentially expensive operations that increase as a function of how many facilities there are, but we don't know exactly where the current bottleneck lies. 

- Does the main culprit seem to be number of facilities, or the amount of history those facilities have? (e.g. does a large number of facilities with little history trigger it?) Does the shadow data feature itself have anything to do with it, or is it mainly a function of how many facilities there are regardless of whether that feature is enabled?
- There is already a feature in place where we attempt to defer the rendering of `FacilityRow` components until they scroll into view. Is this working as expected? (i.e. are these components still doing some expensive work in the render loop before they are actually visible)
- The curve functions (i.e. whatever hooks ultimately call the projection functions in `infection-model/` are known to be expensive. If this is a bottleneck, there are some incremental steps we have already thought about:
    - make these hooks async (i.e. have them return Promises instead of blocking the React render loop)
    - if that doesn't improve things enough, move the expensive SEIR projections to a Cloud Function and replace the in-browser computations with an additional HTTP request
- There are at least two Firestore requests that we do per facility now (one for the facility data and a second one for its history), plus a Cloud Function request for the Rt history. None of these requests individually should have a particularly high data volume, but is the number of requests itself causing some kind of problem? (Doubtful but worth mentioning as a last resort)
- Is there some other expensive or redundant work that is getting repeated per `FacilityRow` that was not previously a known issue?

**Comment by macfarlandian** [comment]
accidentally closed by a partial PR; reopening

**Comment by neeharmb** [comment]
Marking this closed per #664; outstanding performance issues can be filed as separate tickets
