### ISSUE TITLE
Projections for incarcerated cases can exceed a facility's population

### ISSUE THREAD

**Issue by neeharmb** [Recidiviz/covid19-dashboard#658]
**Describe the bug**
Projections for incarcerated cases can exceed a facility's population. 

**To Reproduce**

**Expected behavior**
Projections for both incarcerated should be capped at the facility's population 

**Screenshots**

**Desktop (please complete the following information):**

- OS [e.g. Windows 10]: macOS Catalina
- Browser [e.g. chrome, edge]: Chrome
- Version [e.g. 22]:

**Additional context**

**Comment by neeharmb** [comment]
This is a feature not a bug! The facility in question had a population turnover > 100%, so the projected cases were indeed within its updated total population

**Comment by jessex** [comment]
If you don't have any further question here, @sychang, I believe we are free to close this one?

**Comment by sychang** [comment]
Yes, I love when this happens! Thanks for looking into it, Neehar!
