### ISSUE TITLE
[Shadow data] Rt function fails on input from shadow data

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/covid19-dashboard#690]
Rt failures for facilities created entirely from reference data. The error thrown is not one of the known issues we explicitly catch and return a useful error message for.

Example log output:

```
4:47:44.184 PM Function execution started
4:47:44.199 PM Request JSON (ID tc085zk3upb0): {'dates': ['2020-04-02', '2020-04-03', '2020-04-04', '2020-04-05', '2020-04-06', '2020-04-07', '2020-04-08', '2020-04-09', '2020-04-10', '2020-04-11', '2020-04-12', '2020-04-13', '2020-05-29', '2020-05-30', '2020-05-31', '2020-06-01', '2020-06-02', '2020-06-03', '2020-06-05', '2020-06-06', '2020-06-07', '2020-06-08', '2020-06-09', '2020-06-10', '2020-06-11', '2020-06-12', '2020-06-13', '2020-06-14', '2020-06-15', '2020-06-16', '2020-06-17', '2020-06-18', '2020-06-19', '2020-06-20', '2020-06-22', '2020-06-23', '2020-06-24', '2020-06-25', '2020-06-26', '2020-06-27', '2020-06-28', '2020-06-29', '2020-06-30', '2020-07-01', '2020-07-02', '2020-07-03', '2020-07-06', '2020-07-07', '2020-07-08', '2020-07-09'], 'cases': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 151, 151, 151, 151, 151, 151, 151, 151]}
4:47:46.470 PM /user_code/realtime_rt.py:82: RuntimeWarning: divide by zero encountered in log
4:47:46.470 PM log_likelihood += np.log(denominator)
4:47:48.970 PM /user_code/realtime_rt.py:98: RuntimeWarning: invalid value encountered in greater
4:47:48.970 PM lows, highs = (total_p > p).nonzero()
4:47:48.976 PM Error in cloud function (ID tc085zk3upb0): Traceback (most recent call last):
4:47:48.976 PM File "/user_code/realtime_rt.py", line 142, in compute_r_t
4:47:48.976 PM hdis = highest_density_interval(posteriors, p=.9)
4:47:48.976 PM File "/user_code/realtime_rt.py", line 89, in highest_density_interval
4:47:48.976 PM return pd.DataFrame([highest_density_interval(pmf[col], p=p) for col in pmf],
4:47:48.976 PM File "/user_code/realtime_rt.py", line 89, in <listcomp>
4:47:48.976 PM return pd.DataFrame([highest_density_interval(pmf[col], p=p) for col in pmf],
4:47:48.976 PM File "/user_code/realtime_rt.py", line 101, in highest_density_interval
4:47:48.976 PM best = (highs - lows).argmin()
4:47:48.976 PM ValueError: attempt to get argmin of an empty sequence
4:47:48.976 PM 4:47:48.976 PM During handling of the above exception, another exception occurred:
4:47:48.976 PM 4:47:48.976 PM Traceback (most recent call last):
4:47:48.976 PM File "/user_code/helpers.py", line 46, in wrapped
4:47:48.976 PM function_output = f(request_json)
4:47:48.976 PM File "/user_code/main.py", line 20, in calculate_rt
4:47:48.976 PM result_df = compute_r_t(request_json)
4:47:48.976 PM File "/user_code/realtime_rt.py", line 144, in compute_r_t
4:47:48.976 PM raise ValueError('Unable to compute R(t) with the provided data')
4:47:48.976 PM ValueError: Unable to compute R(t) with the provided data
4:47:48.976 PM 4:47:48.976 PM Response JSON (ID tc085zk3upb0): {"error": "Unable to compute R(t) with the provided data"}
4:47:48.982 PM Function execution took 4800 ms, finished with status code: 500
```

**Comment by macfarlandian** [comment]
Did some digging to identify a cause here: we deal with repeated values by smoothing case counts over a [7 day window](https://github.com/Recidiviz/covid19-dashboard/blob/master/backend/python-functions/realtime_rt.py#L12). If a case count is repeated more than seven times, as happens in the example seem above, this smoothing window is exceeded and the day-over-day case delta will be zero. That in turn leads to the two `RuntimeWarning`s in the log — the probability matrix is all `nan`s, meaning `lows` and `highs` are both empty lists because there are no nonzero values, which is the cause of the `ValueError` on line 101.

Not a blindingly obvious solution to this one, but one way or another the way we deal with repeat cases would have to change in order to accommodate this data shape. It is not completely clear how widespread this issue is, either, but I chose a state more or less at random (Connecticut, in this case) and this error presented in every single facility I included (which was about ten of them)

**Comment by jessex** [comment]
>Not a blindingly obvious solution to this one, but one way or another the way we deal with repeat cases would have to change in order to accommodate this data shape.

Yep, agreed. This data shape is going to becoming increasingly likely to show up as the days march on. I'd suggest syncing with @justkunz to discuss possible solutions here, since it's likely to lead to a non-trivial change to the R(t) methodology.

**Comment by macfarlandian** [comment]
bad news! (in several senses ....) this project has been active long enough that we are even starting to have this problem with user data now. We got a confirmed report of this bug in the wild today from @zacharykatz1 which I think is an indication that we should bump this up on our priority list

**Comment by jessex** [comment]
@macfarlandian, @sychang: we should prioritize this one and decide whether to push the new release now or wait until this has been tackled. As I noted previously, I imagine we need to bring in Justine to consult.

**Comment by sychang** [comment]
(Assuming the new release would launch the shadow data feature)

Chatted with Zak offline and I think it is worth waiting to release until this has been tackled unless this turns out to be a very significant eng lift - can discuss more tomorrow. Couple of pieces of context: 
- States that are actively engaged right now index a fair amount on r(t) when using the app, so will be helpful to be able to let them know if there is a solution (or confirm this a known limitation if it turns out to be a bear).
- There are a few states we are actively engaged with that might start running into this similar issue, and a few others who are already in the middle of porting some of their historical data to the app as we prepare them for report automation, so it is probably safer to wait.

**Comment by macfarlandian** [comment]
I think that makes sense @sychang but to be clear, the new release would not launch the shadow data feature, though it would pave the way for us to turn it on whenever we are ready to. (we still, last I checked, haven't gotten any new data since July, so I am assuming we want to fix that before launching)
