### ISSUE TITLE
Model and compare the output for multiple facilities on the same page

### ISSUE THREAD

**Issue by jessex** [Recidiviz/covid19-dashboard#70]
Add the ability to create and save multiple models per user. On the frontend, we should be able to display multiple models on the same page, with each model named and dated. On the backend, we should be able to save an arbitrary number of named models per user.

High-priority

Initial mocks (another iteration coming later today) https://www.figma.com/proto/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=686%3A134&viewport=395%2C325%2C0.3686773180961609&scaling=min-zoom

**Comment by cawarren** [comment]
Current mocks:
https://www.figma.com/proto/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=735%3A130&viewport=395%2C325%2C0.3686773180961609&scaling=min-zoom

**Comment by cawarren** [comment]
Updated mocks:
https://www.figma.com/file/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=910%3A130
