### ISSUE TITLE
Resolve 2 security vulnerabilities

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/covid19-dashboard#713]
**What needs to be done? Why does it need to be done?**
As of this writing there are two Dependabot alerts on this repo. I believe that both can be safely dismissed. 

The [alert for `y18n`](https://github.com/Recidiviz/covid19-dashboard/security/dependabot/yarn.lock/y18n/open) has evidently been updated to reflect that the versions we have installed are no longer considered vulnerable. The alert has not been dismissed automatically but there seems to be no reason not to close it at this point.

The [alert for `is-svg`](https://github.com/Recidiviz/covid19-dashboard/security/dependabot/yarn.lock/is-svg/open) concerns a transitive Gatsby dependency; it [doesn't sound like](https://github.com/cssnano/cssnano/issues/1019#issuecomment-802182732) there will be a security patch for the line that Gatsby is on (even if we were to upgrade to v3.x). However, according to the maintainers this package is only part of the build tooling and is not actually in use in the bundled application; since there is no actual vulnerability in our deployment I believe this is safe to dismiss as well.

paging @jessex to ratify

**Comment by macfarlandian** [comment]
@jessex FYI, the fix I was able to apply to the `supervision-success-components` package does not apply here; I tried it and the Gatsby build scripts broke.

**Comment by jessex** [comment]
Thanks a lot for the investigation, @macfarlandian. I'm curious about two points:
1. What did the build script breakage look like? What is your rough guess at the remediation path?
2. Do you still feel confident in your PR description about the ability to resolve these two vulnerabilities for now?

**Comment by macfarlandian** [comment]
well, the plot thickens ... 

I just went to go recreate the error and discovered that it was a red herring, caused by some other configuration issue in my local node environment. It turns out that it _is_ possible to simply force yarn to install the newer version. We get a warning about the version not matching some other requirements, but in practice the build tooling does not seem to be affected at all. So ... that's one remediation path.

_deep breath_ 

There are two transitive dependencies on `is-svg`; one is the webfonts plugin, which is a direct dependency and could be pretty easily replaced with another one that doesn't depend on `cssnano` (which is what brings in `is-svg`). Gatsby itself also depends on `cssnano` via a webpack plugin for CSS preprocessing; `cssnano` won't bump `is-svg` until their next major version, which is still in the RC stage; once that is released, the [webpack plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) would have to bump its cssnano version, which may or may not also require a version bump on Gatsby's part. (The next major version of Gatsby uses [a different webpack plugin](https://github.com/webpack-contrib/css-minimizer-webpack-plugin), but it has the same problem; potentially we would have to upgrade to the next major Gatsby to ultimately resolve this, which feels like overkill for this site considering its current state).

_breathe again_

Anyway given all that I think we should just force a resolution via our `package.json`; yarn complains about it, but the only real breaking change in [the 4.x line](https://github.com/sindresorhus/is-svg/releases/tag/v4.0.0) of `is-svg` is that it doesn't support Node 4 anymore, which is not a concern for us. 

Glad you asked! That was an informative visit to the npm underworld, from which I have of course returned unscathed. I can open a PR for this change if that all sounds OK. 

(The `y18n` alert should still just be dismissed, the package we have installed does not have a vulnerability; it seems to have been a dependabot error or something)

**Comment by jessex** [comment]
That is quite a journey! Thanks for taking it on our behalf, @macfarlandian. I think your resolution sounds right. I think this is all low risk anyway given that it's purely build tooling, and given everything you wrote above, but I do think that forcing to a resolved version for `is-svg` is still better than resolving straight-away if we've got a viable path.

And resolving `yi18n` straight-away sounds good, too, given that it's apparently a false positive.
