### ISSUE TITLE
Resolve postcss and grpc-js dependency vulnerabilities

### ISSUE THREAD

**Issue by jessex** [Recidiviz/covid19-dashboard#722]
**What needs to be done? Why does it need to be done?**
There are two fresh, active dependency vulnerabilities for this repo: postcss and @grpc/grpc-js. The latter is a high severity vulnerability so we should resolve these within the next 7 days.

**Additional context**
[Vulnerabilities listed here](https://github.com/Recidiviz/covid19-dashboard/security/dependabot)

**Comment by macfarlandian** [comment]
our postcss version was considered "no longer vulnerable" by dependabot before the advisory magically disappeared; linked PR addresses the other
