### ISSUE TITLE
Resolve ws vulnerability

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/covid19-dashboard#728]
**What needs to be done? Why does it need to be done?**
The `ws` package, a transitive dependency of Gatsby and Jest, has a moderate severity vulnerability as documented [here](https://github.com/Recidiviz/covid19-dashboard/security/dependabot/yarn.lock/ws/open). The package should be updated to a non-vulnerable version. (The patch has been back-ported to both the 6.x and 7.x lines, both of which are in our dependency graph, so this shouldn't require any unusual measures.) 

**Additional context**
FYI @jessex I don't believe there is any live vulnerability, because we don't use any websockets in the application, so I don't think it's urgent that we deploy anything to resolve this.

**Comment by jessex** [comment]
Sounds good, @macfarlandian. Thanks! Tag me on the PR when it's ready.
