### ISSUE TITLE
High-level security vulnerability: set-value

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/covid19-dashboard#733]
**What needs to be done? Why does it need to be done?**
A high-level security vulnerability has been detected by Dependabot in this project.

Per our SLA, high-level security vulnerabilities need to be addressed within 30 days. The deadline for resolution is October 17, 2021.

**Additional context**
https://github.com/Recidiviz/covid19-dashboard/security/dependabot/yarn.lock/set-value/open

**Comment by macfarlandian** [comment]
@phenggeler the linked alert no longer exists - was this resolved elsewhere or was the alert just canceled?

**Comment by phenggeler** [comment]
@macfarlandian - it was likely resolved upstream. The majority of Github Dependabot alerts are “transitive,” meaning they’re pulled in by other dependencies without a direct link between them and the application using them. I'll close this ticket out given that, but in the future feel free to comment that the alert is no longer available and close out the ticket.
