### ISSUE TITLE
Medium-level security vulnerability: nth-check

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/covid19-dashboard#735]
**What needs to be done? Why does it need to be done?**
A medium-level security vulnerability has been detected by Dependabot in this project.

Per our SLA, medium-level security vulnerabilities need to be addressed within 60 days. The deadline for resolution is Nov 21, 2021.

Additional context
https://github.com/Recidiviz/covid19-dashboard/security/dependabot/yarn.lock/nth-check/open

**Comment by jessex** [comment]
@phenggeler updated the ticket description from high-level to medium-level -- think that was just a typo but want to make sure that we're on the same page about the SLA!

**Comment by phenggeler** [comment]
Yes, thanks for catching @jessex
