### ISSUE TITLE
Add "Type of System" input box to split out prison versus jail populations

### ISSUE THREAD

**Issue by jessex** [Recidiviz/covid19-dashboard#74]
Augment the model form to allow targeting prisons versus jails as distinct facility types, and use this information to target specific parameters within the epidemic model.

**Comment by cawarren** [comment]
@jessex I think this is now in the current *Edit Facility* page, as the 'Type of system' dropdown.

If so we can probably close this out.

**Comment by jessex** [comment]
@cawarren I don't believe this actually impacts the epidemic model output yet, though, unless I am mistaken. @macfarlandian to confirm that point. If that is true, does this need to be revised?

**Comment by macfarlandian** [comment]
correct, it's just metadata

**Comment by cawarren** [comment]
I see - I'd rather leave it as metadata for now. I'll file a new issue in a few days that allows us to pull live public facility-specific numbers, which we're collecting in a new spreadsheet.

@jessex @macfarlandian Any concerns w/closing this one out as obsolete?

**Comment by macfarlandian** [comment]
none from me
