### ISSUE TITLE
Re-add updated about page

### ISSUE THREAD

**Issue by jessex** [Recidiviz/covid19-dashboard#77]
Update the about page explaining the current caveats, known issues, and upcoming improvements. @cawarren to provide final copy.

Once this is released, update recidiviz.org/covid with information and instructions about using the web model to augment/replace instructions about the Excel model.

**Comment by sychang** [comment]
We are getting the pieces ready to deprecate the excel model so kicking this one back into motion!

The "About" tab should replace the "Get Involved" tab at the top right of the web app.

There should be 7 sections on this page - open to engineering judgment about organization and navigation (e.g., whether there's left panel navigation for the 7 tabs or 7 stacked sections on the same page) but let me know if it's too ambiguous without mocks and we can get a quick mock up.

1. About
2. Definitions
3. Methodology
4. User Guides
5. FAQ
6. Contact Us
7. Terms of Service

Here is the copy doc, the structure is there but the final wording is still being finalized): https://docs.google.com/document/d/1dbCWxrYC3mProdJUxlNyfiOvzFBfHavhG-rfiYK9VSA/edit#heading=h.lwpe20b6hx98
