### ISSUE TITLE
Provide IE11 support

### ISSUE THREAD

**Issue by jessex** [Recidiviz/covid19-dashboard#80]
The current experience for IE11 users is broken. The landing page shows a partially rendered form behind an infinite loading spinner (though this is likely to change to an infinite spinner over a blank background after a recent change), and the console shows an error message indicating a syntax error in the bundled JS file.

After many hours investigating the issue between @szhu and @jessex, we had to punt on support for now. #72 is adding a banner, ideally as a temporary measure, indicating that IE11 is not currently supported. 

More notes to come on the investigation and attempts made so far...

**Comment by jessex** [comment]
See some attempts from #49 that didn't work.

**Comment by cawarren** [comment]
_Update:_
This is going to move up in priority somewhat this week, as it's currently blocking Montana and Arkansas from using the tool.
