### ISSUE TITLE
Multi-facility support: Develop React components

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/covid19-dashboard#93]
**Is your feature request related to a problem? Please describe.**
The full application shown here will be assembled later this week:
https://www.figma.com/proto/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=735%3A130&viewport=403%2C338%2C0.09717194736003876&scaling=min-zoom

In order to expedite development, we'd like to get most of the small component widgets developed.

**Describe the solution you'd like**
React components for the following elements from the mocks:
- ON/OFF toggles
- On-hover ( ? ) tooltips
- ~~Modal dialog with title, corner X, the 1, 2, 3 steps, and buttons~~ No longer in mocks
- ~~Menus (in the library view)~~ Pushed to next release (multi-scenario)
- The dark-gray 'promo' box
- If time, the facility rows

**Describe alternatives you've considered**
The SWE developing the full design could build these de novo, but this would likely push out the anticipated date of completion.

**Additional context**
@jessex Please take a look and revise this bug if needed. We can also hang FRs for each react component off of this if needed.

**Comment by cawarren** [comment]
Updated mocks (most of the updates are minor, but there are a couple that aren't):
https://www.figma.com/file/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=910%3A130

If you have any questions, feel free to ping me.

**Comment by jessex** [comment]
Everything in the multi-facility release has been completed! Items for the later multi-scenario release are deferred to newer issues. Closing this out.
