### ISSUE TITLE
Add React components for ON/OFF Toggles - MultiFacility page

### ISSUE THREAD

**Issue by daschi** [Recidiviz/covid19-dashboard#98]
**What needs to be done? Why does it need to be done?**
React component for ON/OFF toggles #93 
https://www.figma.com/proto/EGJS9njuKHWdFHUS4lrHA4/%F0%9F%9A%80Recidiviz-CJStatus?node-id=735%3A130&viewport=403%2C338%2C0.09717194736003876&scaling=min-zoom

**Comment by jessex** [comment]
This was accidentally not auto-closed by #101. Closing manually.
